
import type { InventoryEventReason, InventoryItem, InventoryStatus } from './types';
import { convertAmount } from './lib/exchangeRates';

export const CURRENCIES = {
  XAF: { code: 'XAF', symbol: 'FCFA', precision: 0 },
  XOF: { code: 'XOF', symbol: 'CFA', precision: 0 },
  NGN: { code: 'NGN', symbol: '₦', precision: 2 },
  USD: { code: 'USD', symbol: '$ US', precision: 2 },
  CAD: { code: 'CAD', symbol: '$ CAD', precision: 2 },
  EUR: { code: 'EUR', symbol: '€', precision: 2 },
  GBP: { code: 'GBP', symbol: '£', precision: 2 },
} as const;

export type CurrencyCode = keyof typeof CURRENCIES;

export const CURRENCY_CODES = Object.keys(CURRENCIES) as CurrencyCode[];

export const isSupportedCurrency = (value: unknown): value is CurrencyCode =>
  typeof value === 'string' && value in CURRENCIES;

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    loginWelcome: "Smarter Panel",
    loginToAccess: "Login to access your dashboard.",
    login: "Login",
    email: "Email",
    password: "Password",
    signupTitle: "Create your organization",
    signupSubtitle: "Start free with one user and one location. Complete your profile after signup.",
    otpTitle: "Enter verification code",
    otpSubtitle: "We sent a one-time code to your email.",
    inviteTitle: "Accept invitation",
    inviteSubtitle: "Set your password to join the organization.",
    organizationName: "Organization name",
    createOrganization: "Create an organization",
    createAccount: "Create account",
    noAccount: "New here?",
    haveAccount: "Already have an account?",
    pleaseWait: "Please wait…",
    otpCode: "Verification code",
    verifyOtp: "Verify",
    resendOtp: "Resend code",
    inviteToken: "Invite token",
    acceptInvite: "Continue",
    backToLogin: "Back to login",
    forgotPassword: "Forgot password?",
    forgotPasswordTitle: "Reset your password",
    forgotPasswordSubtitle: "Enter your email and we’ll send a verification code.",
    forgotResetTitle: "Choose a new password",
    forgotResetSubtitle: "Enter the code from your email and your new password.",
    sendResetCode: "Send reset code",
    resetPasswordSubmit: "Update password",
    forgotSuccess: "Password updated. You can log in with your new password.",
    devOtpHint: "Dev OTP (SMTP not configured)",
    orgProfileTitle: "Complete organization profile",
    orgProfileSubtitle: "Business details for your organization. Separate from your personal profile.",
    legalName: "Legal name",
    taxId: "Tax ID",
    saveOrgProfile: "Save organization profile",
    orgProfileSaved: "Organization profile saved",
    orgLogoHint: "Upload your organization logo (optional).",
    orgSectionIdentity: "Identity",
    workingCurrency: "Working currency",
    workingCurrencyHint: "Amounts you enter are stored in this currency. The header dropdown only converts for display using live rates.",
    locationCurrency: "Location currency",
    locationCurrencyHint: "Each site books amounts in its own currency. New locations default to the organization working currency.",
    displayCurrency: "Display currency",
    orgSectionContact: "Contact",
    orgSectionAddress: "Address",
    industry: "Industry",
    orgDescription: "About the organization",
    orgEmail: "Organization email",
    city: "City",
    country: "Country",
    postalCode: "Postal code",
    website: "Website",
    organization: "Organization",
    personalProfileTitle: "Complete your personal profile",
    personalProfileSubtitle: "Your personal details within this organization.",
    personalProfileSaved: "Personal profile saved",
    personalInfo: "Personal information",
    jobTitle: "Job title",
    owner: "Owner",
    billing: "Billing",
    billingSubtitle: "Manage your subscription plan and renewals.",
    currentPlan: "Current plan",
    plan: "Plan",
    dueDate: "Due date",
    choosePlan: "Choose a plan",
    subscribe: "Subscribe",
    unlimitedUsers: "Unlimited users",
    unlimitedLocations: "Unlimited locations",
    couponCode: "Coupon code",
    applyCoupon: "Apply",
    assignedCoupons: "Assigned to your org",
    couponApplied: "Coupon applied",
    couponInvalid: "Invalid coupon code",
    couponCheckoutActivated: "Subscription activated with your coupon — no payment required.",
    renewalWindowHint: "You can renew or change plans only within 5 days before or after your due date.",
    probationBanner: "Your organization is on free-tier probation. Only the owner can sign in until you subscribe again.",
    paymentSimulated: "Payment marked successful (dev).",
    sendInvite: "Send invite",
    inviteEmailHint: "Invite a teammate by email. They will receive a link, set their password, and verify with OTP.",
    inviteSent: "Invitation sent",
    inviteResent: "Invitation resent",
    inviteEmailFailed: "Email could not be sent — check SMTP or resend later",
    pendingInvites: "Pending invitations",
    resendInvite: "Resend",
    inviteFromStaff: "Invite from staff",
    dashboard: "Dashboard",
    income: "Income",
    expenses: "Expenses",
    inventory: "Inventory",
    hr: "HR",
    reports: "Reports",
    estimates: "Estimates",
    admin: "Admin",
    logout: "Logout",
    totalIncome: "Total Income",
    totalExpenses: "Total Expenses",
    netBalance: "Net Balance",
    inventoryValue: "Inventory Value",
    recentActivity: "Recent Activity",
    add: "Add",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    editUser: "Edit user",
    saveChanges: "Save changes",
    actions: "Actions",
    source: "Source",
    amount: "Amount",
    date: "Date",
    description: "Description",
    category: "Category",
    item: "Item",
    type: "Type",
    quantity: "Quantity",
    value: "Value",
    firstName: "First Name",
    lastName: "Last Name",
    position: "Position",
    status: "Status",
    documents: "Documents",
    upload: "Upload",
    download: "Download",
    view: "View",
    back: "Back",
    profile: "My Profile",
    address: "Address",
    phone: "Phone",
    gender: "Gender",
    dob: "Date of Birth",
    hireDate: "Hire Date",
    terminationDate: "Termination Date",
    allLocations: "All Locations",
    selectLocation: "Select Location",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordMismatch: "Passwords do not match.",
    passwordChanged: "Password changed successfully.",
    resetPassword: "Reset Password",
    resetSuccess: "Password reset. Temp password: ",
    oldPassword: "Current Password",
    oldPasswordRequired: "Current password is required",
    confirmDelete: "Confirm Delete",
    deactivate: "Deactivate",
    reactivate: "Reactivate",
    remove: "Remove",
    confirmDeactivateUser: "Deactivate this user? They will no longer be able to log in.",
    confirmRemoveUser: "Permanently remove this user? This cannot be undone.",
    userDeactivated: "User deactivated",
    userReactivated: "User reactivated",
    userRemoved: "User removed",
    active: "Active",
    inactive: "Inactive",
    deleteStaffConfirm: "Are you sure you want to delete this staff member?",
    noUserAccount: "This staff member has no user account",
    uploadDocument: "Upload Document",
    documentName: "Document Name",
    documentType: "Document Type",
    selectFile: "Select File",
    updatePermissions: "Update Permissions",
    positions: "Positions",
    noDocuments: "No documents uploaded yet",
    permissionsSelected: "permissions selected",
    perm_viewDashboard: "View Dashboard",
    perm_viewIncome: "View Income",
    perm_addIncome: "Add Income",
    perm_deleteIncome: "Delete Income",
    perm_viewExpenses: "View Expenses",
    perm_addExpenses: "Add Expenses",
    perm_deleteExpenses: "Delete Expenses",
    perm_manageCategories: "Manage Categories",
    perm_viewInventory: "View Inventory",
    perm_addInventory: "Add Inventory",
    perm_updateInventory: "Update Inventory / Report Incidents",
    perm_deleteInventory: "Delete Inventory",
    perm_manageTypes: "Manage Inventory Types",
    perm_viewHR: "View HR",
    perm_addHR: "Add Employee",
    perm_updateHR: "Update Employee",
    perm_deleteHR: "Delete Employee",
    perm_manageHRUploads: "Manage HR Documents",
    perm_managePositions: "Manage Positions",
    perm_manageDocs: "Manage Documents",
    perm_viewReports: "View Reports",
    perm_viewEstimates: "View Estimates",
    perm_addEstimates: "Add Estimates",
    perm_updateEstimates: "Update Estimates",
    perm_deleteEstimates: "Delete Estimates",
    perm_manageEstimateTemplates: "Manage Estimate Templates",
    perm_viewAdmin: "Admin Access",
    perm_manageAdminUsers: "Admin: User Management tab",
    perm_manageAdminRoles: "Admin: Role Management tab",
    perm_manageAdminConfig: "Admin: Config (locations, categories, types, positions, sources, descriptions, storage places)",
    adminNoSubPermission: "You don't have permission to manage any settings. Contact an administrator to get access to User Management, Role Management, or Config.",
    perm_allLocations: "All Locations Access",
    manage_users: "Manage Users (create, edit, delete, reset password for any user)",
    perm_resetUserPassword: "Reset User Password (users in your location only)",
    perm_deactivateUser: "Deactivate users",
    perm_removeUser: "Remove users",
    errorFillFields: "Please fill all required fields.",
    errorDateFuture: "Date cannot be in the future.",
    errorDatePast: "Date cannot be older than 7 days.",
    errorNoLocation: "Please select a specific location.",
    userManagement: "User Management",
    roleManagement: "Role Management",
    locationManagement: "Locations",
    configManagement: "Configurations",
    generateReport: "Generate Report",
    forecast: "Financial Forecast",
    monthly: "Monthly",
    quarterly: "Quarterly",
    yearly: "Yearly",
    allTime: "All Time",
    dateRange: "Date Range",
    dateFrom: "From",
    dateTo: "To",
    last7Days: "Last 7 days",
    thisMonth: "This month",
    thisYear: "This year",
    last12Months: "Last 12 months",
    incomeVsExpenses: "Income vs Expenses",
    incomeBySource: "Income by Source",
    expensesByCategory: "Expenses by Category",
    financialOverview: "Financial Overview",
    financialHealth: "Financial Health",
    netTrend: "Net Balance Trend",
    showCharts: "Show charts",
    hideCharts: "Hide charts",
    downloadCSV: "Download CSV",
    downloadExcel: "Download Excel",
    forecastTitle: "Projected Financials",
    forecastDesc: "Based on historical average",
    managePermissions: "Manage Permissions",
    roleName: "Role Name",
    permissions: "Permissions",
    expenseCategories: "Expense Categories",
    inventoryTypes: "Inventory Types",
    incomeSources: "Income Sources",
    expenseDescriptions: "Expense Descriptions",
    storagePlaces: "Storage Places",
    name: "Name",
    nameFr: "Name (FR)",
    metric: "Metric",
    allMetrics: "All Metrics",
    incomeOnly: "Income Only",
    expensesOnly: "Expenses Only",
    inventoryOnly: "Inventory",
    specificLocation: "Specific Location",
    changePhoto: "Change Photo",
    updateProfile: "Update Profile",
    mandatoryReset: "Security Alert: You must change your password to continue.",
    hierarchyForbidden: "You cannot modify or delete a user who is above you in the hierarchy.",
    locked24hMessage: "Cannot modify or delete after 24 hours (fraud prevention).",
    auditLogs: "Audit Logs",
    perm_viewAuditLogs: "View Audit Logs",
    filterByLocation: "Location",
    filterByUser: "User",
    searchByName: "Search by name",
    filterByPosition: "Position",
    allPositions: "All positions",
    listView: "List view",
    gridView: "Grid view",
    auditAction: "Action",
    auditResource: "Resource",
    auditTime: "Time",
    auditDetails: "Details",
    auditUser: "User",
    auditLocation: "Location",
    noAuditLogs: "No audit logs found.",
    applyFilters: "Apply",
    clearFilters: "Clear",
    notifications: "Notifications",
    perm_viewNotifications: "View Notifications",
    noNotifications: "No notifications",
    themeToggle: "Toggle light/dark mode",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    errorNoInventory: "No inventory item selected.",
    inventoryDeleteConfirm: "Delete inventory item?",
    inventoryDeleteConfirmMsg: "Are you sure you want to delete this inventory item?",
    inventoryUpdateTitle: "Edit inventory item",
    inventoryReportIncident: "Report incident",
    inventoryOnHand: "On hand",
    inventoryOnHandShort: "Qty",
    inventoryUnitValue: "Unit value",
    inventoryUnitValueShort: "Unit",
    inventoryTotal: "Total",
    inventoryTotalShort: "Total",
    inventoryStatus: "Status",
    inventoryExpiry: "Expiry",
    inventoryLastUpdated: "Last updated",
    inventoryLastUpdatedShort: "Updated",
    inventoryExpiresOn: "Expires on",
    inventoryNotes: "Notes",
    inventoryImage: "Item image",
    inventoryStoragePlace: "Storage place",
    inventoryStoragePlaceShort: "Place",
    inventoryStoragePlaceHint: "Shelf, bin, cold room, zone…",
    inventorySiteLabel: "Business site",
    inventoryImageUploadFailed: "Failed to upload item image.",
    inventoryChangeImage: "Change image",
    inventorySearch: "Search items…",
    inventoryFilterStatus: "Status",
    inventoryFilterType: "Type",
    inventoryFilterAll: "All",
    inventoryExpiringSoon: "Expiring within 30 days",
    inventoryStatus_available: "Available",
    inventoryStatus_damaged: "Damaged",
    inventoryStatus_expired: "Expired",
    inventoryStatus_missing: "Missing",
    inventoryReason_damaged: "Damaged / broken",
    inventoryReason_expired: "Expired / spoiled",
    inventoryReason_stolen: "Stolen / missing",
    inventoryReason_restored: "Restored / found",
    inventoryReason_adjustment: "Quantity adjustment",
    inventoryIncidentReason: "Reason",
    inventoryIncidentQty: "Quantity",
    inventoryIncidentNote: "Note",
    inventoryIncidentNoteRequired: "A note is required for damaged or stolen incidents.",
    inventoryIncidentQtyInvalid: "Enter a valid quantity for this incident.",
    inventoryIncidentSuccess: "Incident recorded.",
    inventoryIncidentFailed: "Failed to record incident.",
    inventoryAdded: "Inventory item added successfully",
    inventoryUpdated: "Inventory item updated successfully",
    inventoryRemoved: "Inventory item removed successfully",
    inventoryNoPermAdd: "You do not have permission to add inventory items.",
    inventoryNoPermUpdate: "You do not have permission to update inventory.",
    inventoryNoPermDelete: "You do not have permission to delete inventory items.",
    inventoryHealth: "Inventory health",
    inventoryAvailableValue: "Available value",
    inventoryLossValue: "Loss value",
    inventoryUnitsLost: "Units lost",
    inventoryDamagedUnits: "Damaged",
    inventoryExpiredUnits: "Expired",
    inventoryStolenUnits: "Stolen",
    inventoryExpiringSoonCount: "Expiring soon",
    inventoryLossesByReason: "Inventory losses by reason",
    inventoryLossesSheet: "Inventory Losses",
    inventoryNoItems: "No inventory items match your filters.",
    newHire: "New hire",
    staffTerminationDate: "Termination date set",
    staffDeleted: "Staff account deleted",
    incomeDeleted: "Income deleted",
    expenseDeleted: "Expense deleted",
    inventoryDeleted: "Inventory item deleted",
    reportDownloaded: "Report downloaded",
    newEstimate: "New estimate",
    editEstimate: "Edit estimate",
    estimateTitle: "Title",
    estimateNumber: "Estimate #",
    estimateStatus: "Status",
    estimateCustomer: "Customer",
    estimateBusiness: "Business",
    estimateLineItems: "Line items",
    estimatePreview: "Preview",
    estimateTemplate: "Template",
    estimateIndustryTemplates: "Industry templates",
    estimateUserTemplates: "Your templates",
    archiveAsTemplate: "Archive as template",
    estimateLogo: "Logo",
    primaryColor: "Primary color",
    accentColor: "Accent color",
    estimateLayout: "Layout",
    layoutClassic: "Classic",
    layoutModern: "Modern",
    layoutCompact: "Compact",
    validUntil: "Valid until",
    issueDate: "Issue date",
    taxRate: "Tax %",
    subtotal: "Subtotal",
    taxAmount: "Tax",
    total: "Total",
    unitPrice: "Unit price",
    unit: "Unit",
    lineTotal: "Line total",
    terms: "Terms",
    notes: "Notes",
    exportCsv: "Export CSV",
    exportExcel: "Export Excel",
    exportPdf: "Print / PDF",
    copyPlainText: "Copy text",
    estimateDraft: "Draft",
    estimateSent: "Sent",
    estimateAccepted: "Accepted",
    estimateRejected: "Rejected",
    estimateArchived: "Archived",
    noEstimates: "No estimates yet.",
    searchEstimates: "Search estimates…",
    addLineItem: "Add line",
    removeLineItem: "Remove",
    customerName: "Customer name",
    customerEmail: "Customer email",
    customerPhone: "Customer phone",
    customerAddress: "Customer address",
    businessName: "Business name",
    businessAddress: "Business address",
    businessPhone: "Business phone",
    estimateSaved: "Estimate saved",
    estimateDeleted: "Estimate deleted",
    templateArchived: "Saved as template",
    pickTemplate: "Start from template",
    blankEstimate: "Blank estimate",

        // Marketing / Navigation
    navDescription: "Description",
    navPartners: "Our partners",
    navFeatures: "Features",
    navTestimonials: "Testimonials",
    navFaq: "FAQ",
    navBlog: "Blog",
    getStarted: "Get started",
    getItNow: "Get it now",
    trustedBy: "Trusted by the best companies",

    // Hero
    heroTitle: "Your new business companion ",
    heroHighlight: "SMARTER PANEL",
    heroSubtitle:
      "SMARTER PANEL is a comprehensive HR and Accounting management dashboard for business operations. Features include income/expense tracking, inventory management, staff administration, and financial reporting.",

    // Highlights
    highlightsTitle: "Highlights",
    highlightsDesc:
      "Explore why our product stands out: adaptability, durability, user-friendly design, and innovation. Enjoy reliable customer support and precision in every detail.",
    highlightAdaptableTitle: "Adaptable performance",
    highlightAdaptableDesc:
      "Our product effortlessly adjusts to your needs, boosting efficiency and simplifying your tasks.",
    highlightBuiltToLastTitle: "Built to last",
    highlightBuiltToLastDesc:
      "Experience unmatched durability that goes above and beyond with lasting investment.",
    highlightUserExperienceTitle: "Great user experience",
    highlightUserExperienceDesc:
      "Integrate our product into your routine with an intuitive and easy-to-use interface.",
    highlightInnovativeTitle: "Innovative functionality",
    highlightInnovativeDesc:
      "Stay ahead with features that set new standards, addressing your evolving needs better than the rest.",
    highlightSupportTitle: "Reliable support",
    highlightSupportDesc:
      "Count on our responsive customer support, offering assistance that goes beyond the purchase.",
    highlightPrecisionTitle: "Precision in every detail",
    highlightPrecisionDesc:
      "Enjoy a meticulously crafted product where small touches make a significant impact on your overall experience.",

    // Features
    featuresTitle: "Product features",
    featuresDesc:
      "Provide a brief overview of the key features of the product. For example, you could list the number of features, their types or benefits, and add-ons.",
    featureDashboardTitle: "Dashboard overview, financials, HR, operations and more features capabilities",
    featureDashboardDesc:
      "Our solution give users easy acces tools to manage their activity, from financials to operations, all in one place.",
    featureOfflineTitle: "Offline functionality integration",
    featureOfflineDesc:
      "Our product could provide offline functionality, allowing users to continue working even when they are not connected to the internet.",
    featureDevicesTitle: "Available for all devices",
    featureDevicesDesc:
      "This item could let users know the product is available on all platforms, such as web, mobile, and desktop.",

    // Testimonials
    testimonialsTitle: "Testimonials",
    testimonialsDesc:
      "See what our customers love about our products. Discover how we excel in efficiency, durability, and satisfaction. Join us for quality, innovation, and reliable support.",
    testimonial1Name: "Remy Sharp",
    testimonial1Occupation: "Senior Engineer",
    testimonial1Text:
      "I absolutely love how versatile this product is! Whether I'm tackling work projects or indulging in my favorite hobbies, it seamlessly adapts to my changing needs. Its intuitive design has truly enhanced my daily routine, making tasks more efficient and enjoyable.",
    testimonial2Name: "Travis Howard",
    testimonial2Occupation: "Lead Product Designer",
    testimonial2Text:
      "One of the standout features of this product is the exceptional customer support. In my experience, the team behind this product has been quick to respond and incredibly helpful. It's reassuring to know that they stand firmly behind their product.",
    testimonial3Name: "Cindy Baker",
    testimonial3Occupation: "CTO",
    testimonial3Text:
      "The level of simplicity and user-friendliness in this product has significantly simplified my life. I appreciate the creators for delivering a solution that not only meets but exceeds user expectations.",
    testimonial4Name: "Julia Stewart",
    testimonial4Occupation: "Senior Engineer",
    testimonial4Text:
      "I appreciate the attention to detail in the design of this product. The small touches make a big difference, and it's evident that the creators focused on delivering a premium experience.",
    testimonial5Name: "John Smith",
    testimonial5Occupation: "Product Designer",
    testimonial5Text:
      "I've tried other similar products, but this one stands out for its innovative features. It's clear that the makers put a lot of thought into creating a solution that truly addresses user needs.",
    testimonial6Name: "Daniel Wolf",
    testimonial6Occupation: "CDO",
    testimonial6Text:
      "The quality of this product exceeded my expectations. It's durable, well-designed, and built to last. Definitely worth the investment!",

    // Pricing
    pricingTitle: "Pricing",
    pricingDesc: "Chooze the subscription plan that's right for you and your team.",
    planFreeTitle: "Free",
    // planFreeDescription: ["1 user included", "1 location included", "Unlimited storage", "Report download", "Email support", "24/7 customer support"],
    planStarterTitle: "Starter",
    // planStarterDescription: ["2 users included", "2 locations included", "Unlimited storage", "Help center access", "report download", "Email support", "24/7 customer support"],
    planGrowthTitle: "Growth",
    // planGrowthDescription: ["5 users included", "3 locations included", "Unlimited storage", "Report download", "Help center access", "Priority email support", "Best deals", "24/7 customer support"],
    planEnterpriseTitle: "Enterprise",
    // planEnterpriseDescription: ["Unlimited users", "Unlimited locations", "unlimited storage", "Help center access priority", "Dedicated team", "Report download", "Phone & email support", "Priority email support", "24/7 customer support"],
    // In TRANSLATIONS.en
    planFreeDescription: "1 user included\n1 location included\nUnlimited storage\nReport download\nEmail support\n24/7 customer support",
    planStarterDescription: "2 users included\n2 locations included\nUnlimited storage\nHelp center access\nreport download\nEmail support\n24/7 customer support",
    planGrowthDescription: "5 users included\n3 locations included\nUnlimited storage\nReport download\nHelp center access\nPriority email support\nBest deals\n24/7 customer support",
    planEnterpriseDescription: "Unlimited users\nUnlimited locations\nunlimited storage\nHelp center access priority\nDedicated team\nReport download\nPhone & email support\nPriority email support\n24/7 customer support",
    planFreeButton: "Sign up for free",
    planStarterButton: "Get started",
    planGrowthButton: "Start now",
    planEnterpriseButton: "Go smarter",
    perMonth: "/ month",

    // FAQ
    faqTitle: "Frequently asked questions",
    faqQuestion1: "How do I sign in? What is the OTP flow?",
    faqAnswer1:
      "Sign in with your email and password, then verify using the one-time code sent to your email. Use the <strong>Resend code</strong> button if the code does not arrive. The app uses email OTP rather than password-only authentication for added security.",
    faqQuestion2: "I didn't receive an OTP or invite email — what should I do?",
    faqAnswer2:
      "Check your spam/junk folder and confirm the email is correct. Ask the sender to resend the invite or code. If the app shows SMTP or delivery errors, contact support or your organization administrator.",
    faqQuestion3: "How does offline mode and syncing work?",
    faqAnswer3:
      "The PWA can queue certain creates, updates and uploads in the browser (IndexedDB) while offline. When you reconnect the queued actions are synced to the server. Avoid clearing site data until sync completes to prevent data loss.",
    faqQuestion4: "Where can I find the Privacy Policy and Terms? How do I request data deletion?",
    faqAnswer4:
      "Privacy Policy and Terms links are available in the footer and on the Help Center. For data export or deletion requests contact the privacy contact listed on the Privacy Policy page (or email the organization owner/admin to initiate the request).",

    // Footer
    footerDescription: "Smarter Panel is a powerful and user-friendly platform that helps businesses streamline their operations.",
    footerProduct: "Product",
    footerDescriptionLink: "Description",
    footerFeaturesLink: "Features",
    footerTestimonialsLink: "Testimonials",
    footerPricingLink: "Pricing",
    footerHelpCenter: "Help Center",
    footerFaq: "FAQs",
    footerCompany: "Company",
    footerAboutUs: "About us",
    footerCareers: "Careers",
    footerPress: "Press",
    footerPrivacyPolicy: "Privacy Policy",
    footerTermsOfService: "Terms of Service",
    footerCopyright: "Copyright © {year} Smarter Panel",
    and: "and the",

    // Help Center page
    helpTitle: "Help Center — Smarter Panel",
    helpIntro:
      "Practical guide to using Smarter Panel. Below are topics to help you get started, troubleshoot common issues, and understand product limits and rules. For privacy and legal terms see the links at the bottom of the page.",
    helpGettingStartedTitle: "Getting started",
    helpGettingStartedText:
      "Create an organization from the login screen, set a password (min 6 chars) and verify using the code sent to your email. Complete the organization and personal profiles as prompted.",
    helpSignInTitle: "Sign in, OTP, and password reset",
    helpSignInText:
      "Smarter Panel uses email one-time codes (OTP) for login, signup and password reset. If you don’t receive a code check spam/junk and use the resend button. In dev environments a dev OTP may be shown on screen when SMTP is not configured.",
    helpInvitationsTitle: "Invitations",
    helpInvitationsText:
      "Admins invite users from Admin → Users. Invitees accept using the link or token in the email, set a password, then verify using an email code.",
    helpOfflineTitle: "Offline mode",
    helpOfflineText:
      "The PWA supports offline queues for some creates/updates/uploads. If you work offline, items are queued in the browser (IndexedDB) and synchronized when connectivity returns. Clearing site data can remove unsynced work.",
    helpSupportTitle: "Support",
    helpSupportText:
      "Use the floating Support chat in the app or email our support team at {email}.",
    helpDocLink: "For the full documentation see the ",

    // Privacy Policy page
    privacyTitle: "Privacy Policy — Smarter Panel",
    privacyIntro:
      "This page summarizes how Smarter Panel collects and processes data. This is a product-facing draft — have legal review for production.",
    privacyWhatCollectTitle: "What we collect",
    privacyWhatCollectText:
      "We collect account/profile data, organization data, operational business data (income, expenses, inventory, HR), billing and support communications, authentication data (OTP and tokens), and client-side caches for offline support.",
    privacyWhyProcessTitle: "Why we process data",
    privacyWhyProcessText:
      "To provide and secure the Service, support onboarding, billing, offline continuity, and legal compliance. We do not sell your personal information.",
    privacySharingTitle: "Sharing",
    privacySharingText:
      "We share data with your organization, our payment processor, email providers, hosting infrastructure, and when required by law.",
    privacyRetentionTitle: "Retention & deletion",
    privacyRetentionText:
      "Active data is retained while your organization uses the Service. Device caches persist until cleared. Contact privacy for export or deletion requests.",
    privacyContact: "Contact: {email}",

    // Terms page
    termsTitle: "Terms and Conditions — Smarter Panel",
    termsIntro:
      "These terms govern access and use of Smarter Panel. This is a product draft and should be reviewed by legal before publishing.",
    termsAccountsTitle: "Accounts and eligibility",
    termsAccountsText:
      "Organizations and owner accounts are responsible for profiles, users, subscriptions and compliance with these Terms.",
    termsSubscriptionsTitle: "Subscriptions and billing",
    termsSubscriptionsText:
      "Plans may limit users and locations. Owners manage billing and can upgrade or renew through the Billing UI. Checkout may use a third party payment provider.",
    termsRulesTitle: "Product rules",
    termsRulesText:
      "The product enforces practical rules such as 7-day date limits and 24-hour edit/delete locks on many records to reduce fraud and errors.",
    termsContact: "Contact legal: {email}",
  },
  fr: {
    loginWelcome: "Smarter Panel",
    loginToAccess: "Connectez-vous pour accéder.",
    login: "Connexion",
    email: "Email",
    password: "Mot de passe",
    signupTitle: "Créer votre organisation",
    signupSubtitle: "Commencez gratuitement avec un utilisateur et un site. Complétez le profil après l'inscription.",
    otpTitle: "Code de vérification",
    otpSubtitle: "Nous avons envoyé un code unique à votre e-mail.",
    inviteTitle: "Accepter l'invitation",
    inviteSubtitle: "Définissez votre mot de passe pour rejoindre l'organisation.",
    organizationName: "Nom de l'organisation",
    createOrganization: "Créer une organisation",
    createAccount: "Créer le compte",
    noAccount: "Nouveau ?",
    haveAccount: "Déjà un compte ?",
    pleaseWait: "Veuillez patienter…",
    otpCode: "Code de vérification",
    verifyOtp: "Vérifier",
    resendOtp: "Renvoyer le code",
    inviteToken: "Jeton d'invitation",
    acceptInvite: "Continuer",
    backToLogin: "Retour à la connexion",
    forgotPassword: "Mot de passe oublié ?",
    forgotPasswordTitle: "Réinitialiser le mot de passe",
    forgotPasswordSubtitle: "Saisissez votre e-mail et nous enverrons un code de vérification.",
    forgotResetTitle: "Choisir un nouveau mot de passe",
    forgotResetSubtitle: "Entrez le code reçu par e-mail et votre nouveau mot de passe.",
    sendResetCode: "Envoyer le code",
    resetPasswordSubmit: "Mettre à jour le mot de passe",
    forgotSuccess: "Mot de passe mis à jour. Vous pouvez vous connecter.",
    devOtpHint: "OTP dev (SMTP non configuré)",
    orgProfileTitle: "Compléter le profil de l'organisation",
    orgProfileSubtitle: "Informations de l'entreprise. Séparé de votre profil personnel.",
    legalName: "Raison sociale",
    taxId: "N° fiscal",
    saveOrgProfile: "Enregistrer le profil organisation",
    orgProfileSaved: "Profil organisation enregistré",
    orgLogoHint: "Téléverser le logo de l'organisation (optionnel).",
    orgSectionIdentity: "Identité",
    workingCurrency: "Devise de travail",
    workingCurrencyHint: "Les montants saisis sont enregistrés dans cette devise. Le sélecteur de l’en-tête ne convertit que l’affichage avec des taux en direct.",
    locationCurrency: "Devise du site",
    locationCurrencyHint: "Chaque site enregistre les montants dans sa propre devise. Les nouveaux sites héritent de la devise de l’organisation.",
    displayCurrency: "Devise d’affichage",
    orgSectionContact: "Contact",
    orgSectionAddress: "Adresse",
    industry: "Secteur d'activité",
    orgDescription: "À propos de l'organisation",
    orgEmail: "E-mail de l'organisation",
    city: "Ville",
    country: "Pays",
    postalCode: "Code postal",
    website: "Site web",
    organization: "Organisation",
    personalProfileTitle: "Compléter votre profil personnel",
    personalProfileSubtitle: "Vos informations personnelles au sein de cette organisation.",
    personalProfileSaved: "Profil personnel enregistré",
    personalInfo: "Informations personnelles",
    jobTitle: "Poste",
    owner: "Propriétaire",
    billing: "Abonnement",
    billingSubtitle: "Gérez votre forfait et les renouvellements.",
    currentPlan: "Forfait actuel",
    plan: "Forfait",
    dueDate: "Échéance",
    choosePlan: "Choisir un forfait",
    subscribe: "S'abonner",
    unlimitedUsers: "Utilisateurs illimités",
    unlimitedLocations: "Sites illimités",
    couponCode: "Code promo",
    applyCoupon: "Appliquer",
    assignedCoupons: "Assignés à votre organisation",
    couponApplied: "Code promo appliqué",
    couponInvalid: "Code promo invalide",
    couponCheckoutActivated: "Abonnement activé avec votre code promo — aucun paiement requis.",
    renewalWindowHint: "Renouvellement ou changement de forfait uniquement dans les 5 jours avant/après l'échéance.",
    probationBanner: "Votre organisation est en probation (forfait gratuit). Seul le propriétaire peut se connecter jusqu'à un nouvel abonnement.",
    paymentSimulated: "Paiement marqué réussi (dev).",
    sendInvite: "Envoyer une invitation",
    inviteEmailHint: "Invitez un collaborateur par e-mail. Il recevra un lien, choisira son mot de passe et vérifiera par OTP.",
    inviteSent: "Invitation envoyée",
    inviteResent: "Invitation renvoyée",
    inviteEmailFailed: "L'e-mail n'a pas pu être envoyé — vérifiez SMTP ou renvoyez plus tard",
    pendingInvites: "Invitations en attente",
    resendInvite: "Renvoyer",
    inviteFromStaff: "Inviter depuis le personnel",
    dashboard: "Tableau de Bord",
    income: "Revenus",
    expenses: "Dépenses",
    inventory: "Inventaire",
    hr: "RH",
    reports: "Rapports",
    estimates: "Devis",
    admin: "Admin",
    logout: "Déconnexion",
    totalIncome: "Revenus Totaux",
    totalExpenses: "Dépenses Totales",
    netBalance: "Solde Net",
    inventoryValue: "Valeur Inventaire",
    recentActivity: "Activité Récente",
    add: "Ajouter",
    delete: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    editUser: "Modifier l'utilisateur",
    saveChanges: "Enregistrer les modifications",
    actions: "Actions",
    source: "Source",
    amount: "Montant",
    date: "Date",
    description: "Description",
    category: "Catégorie",
    item: "Article",
    type: "Type",
    quantity: "Quantité",
    value: "Valeur",
    firstName: "Prénom",
    lastName: "Nom",
    position: "Poste",
    status: "Statut",
    documents: "Documents",
    upload: "Téléverser",
    download: "Télécharger",
    view: "Voir",
    back: "Retour",
    profile: "Mon Profil",
    address: "Adresse",
    phone: "Téléphone",
    gender: "Sexe",
    dob: "Date de Naissance",
    hireDate: "Date d'embauche",
    terminationDate: "Date de fin de contrat",
    allLocations: "Tous les Sites",
    selectLocation: "Choisir un site",
    changePassword: "Changer mot de passe",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer mot de passe",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    passwordChanged: "Mot de passe changé avec succès.",
    resetPassword: "Réinitialiser MDP",
    resetSuccess: "Réinitialisé. MDP temp: ",
    oldPassword: "Mot de passe actuel",
    oldPasswordRequired: "Le mot de passe actuel est requis",
    confirmDelete: "Confirmer la suppression",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    remove: "Supprimer",
    confirmDeactivateUser: "Désactiver cet utilisateur ? Il ne pourra plus se connecter.",
    confirmRemoveUser: "Supprimer définitivement cet utilisateur ? Cette action est irréversible.",
    userDeactivated: "Utilisateur désactivé",
    userReactivated: "Utilisateur réactivé",
    userRemoved: "Utilisateur supprimé",
    active: "Actif",
    inactive: "Inactif",
    deleteStaffConfirm: "Êtes-vous sûr de vouloir supprimer ce membre du personnel?",
    noUserAccount: "Ce membre du personnel n'a pas de compte utilisateur",
    uploadDocument: "Téléverser un document",
    documentName: "Nom du document",
    documentType: "Type de document",
    selectFile: "Sélectionner un fichier",
    updatePermissions: "Mettre à jour les permissions",
    positions: "Postes",
    noDocuments: "Aucun document téléversé",
    permissionsSelected: "permissions sélectionnées",
    perm_viewDashboard: "Voir Tableau de Bord",
    perm_viewIncome: "Voir Revenus",
    perm_addIncome: "Ajouter Revenu",
    perm_deleteIncome: "Supprimer Revenu",
    perm_viewExpenses: "Voir Dépenses",
    perm_addExpenses: "Ajouter Dépense",
    perm_deleteExpenses: "Supprimer Dépense",
    perm_manageCategories: "Gérer Catégories",
    perm_viewInventory: "Voir Inventaire",
    perm_addInventory: "Ajouter Inventaire",
    perm_updateInventory: "Modifier inventaire / signaler incidents",
    perm_deleteInventory: "Supprimer Inventaire",
    perm_manageTypes: "Gérer Types Inv.",
    perm_viewHR: "Voir RH",
    perm_addHR: "Ajouter Employé",
    perm_updateHR: "Modifier Employé",
    perm_deleteHR: "Supprimer Employé",
    perm_manageHRUploads: "Gérer Documents RH",
    perm_managePositions: "Gérer Postes",
    perm_manageDocs: "Gérer Documents",
    perm_viewReports: "Voir Rapports",
    perm_viewEstimates: "Voir Devis",
    perm_addEstimates: "Ajouter Devis",
    perm_updateEstimates: "Modifier Devis",
    perm_deleteEstimates: "Supprimer Devis",
    perm_manageEstimateTemplates: "Gérer modèles de devis",
    perm_viewAdmin: "Accès Admin",
    perm_manageAdminUsers: "Admin: onglet Gestion des utilisateurs",
    perm_manageAdminRoles: "Admin: onglet Gestion des rôles",
    perm_manageAdminConfig: "Admin: Config (sites, catégories, types, postes, sources, descriptions, emplacements)",
    adminNoSubPermission: "Vous n'avez pas la permission de gérer les paramètres. Contactez un administrateur pour accéder à la Gestion des utilisateurs, des rôles ou de la Config.",
    perm_allLocations: "Accès à Tous Les Sites",
    manage_users: "Gérer les utilisateurs (créer, modifier, supprimer, réinitialiser MDP pour tout utilisateur)",
    perm_resetUserPassword: "Réinitialiser le mot de passe (utilisateurs de votre site uniquement)",
    perm_deactivateUser: "Désactiver des utilisateurs",
    perm_removeUser: "Supprimer des utilisateurs",
    errorFillFields: "Veuillez remplir tous les champs.",
    errorDateFuture: "La date ne peut pas être dans le futur.",
    errorDatePast: "La date ne peut pas dépasser 7 jours.",
    errorNoLocation: "Veuillez sélectionner un site spécifique.",
    userManagement: "Gestion Utilisateurs",
    roleManagement: "Gestion Rôles",
    locationManagement: "Sites",
    configManagement: "Configurations",
    generateReport: "Générer Rapport",
    forecast: "Prévisions Financières",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    yearly: "Annuel",
    allTime: "Tout",
    dateRange: "Période",
    dateFrom: "Du",
    dateTo: "Au",
    last7Days: "7 derniers jours",
    thisMonth: "Ce mois",
    thisYear: "Cette année",
    last12Months: "12 derniers mois",
    incomeVsExpenses: "Revenus vs Dépenses",
    incomeBySource: "Revenus par source",
    expensesByCategory: "Dépenses par catégorie",
    financialOverview: "Vue financière",
    financialHealth: "Santé financière",
    netTrend: "Tendance du solde net",
    showCharts: "Afficher les graphiques",
    hideCharts: "Masquer les graphiques",
    downloadCSV: "Télécharger CSV",
    downloadExcel: "Télécharger Excel",
    forecastTitle: "Projections Financières",
    forecastDesc: "Basé sur la moyenne historique",
    managePermissions: "Gérer Permissions",
    roleName: "Nom du Rôle",
    permissions: "Permissions",
    expenseCategories: "Catégories Dépenses",
    inventoryTypes: "Types Inventaire",
    incomeSources: "Sources de revenus",
    expenseDescriptions: "Descriptions de dépenses",
    storagePlaces: "Emplacements de stockage",
    name: "Nom",
    nameFr: "Nom (FR)",
    metric: "Métrique",
    allMetrics: "Toutes Métriques",
    incomeOnly: "Revenus Seuls",
    expensesOnly: "Dépenses Seules",
    inventoryOnly: "Inventaire",
    specificLocation: "Site Spécifique",
    changePhoto: "Changer Photo",
    updateProfile: "Mettre à jour Profil",
    mandatoryReset: "Alerte Sécurité: Vous devez changer votre mot de passe pour continuer.",
    hierarchyForbidden: "Vous ne pouvez pas modifier ou supprimer un utilisateur au-dessus de vous dans la hiérarchie.",
    locked24hMessage: "Modification et suppression interdites après 24 h (prévention des fraudes).",
    auditLogs: "Journaux d'audit",
    perm_viewAuditLogs: "Voir les journaux d'audit",
    filterByLocation: "Site",
    filterByUser: "Utilisateur",
    searchByName: "Rechercher par nom",
    filterByPosition: "Poste",
    allPositions: "Tous les postes",
    listView: "Vue liste",
    gridView: "Vue grille",
    auditAction: "Action",
    auditResource: "Ressource",
    auditTime: "Heure",
    auditDetails: "Détails",
    auditUser: "Utilisateur",
    auditLocation: "Site",
    noAuditLogs: "Aucun journal d'audit.",
    applyFilters: "Appliquer",
    clearFilters: "Effacer",
    notifications: "Notifications",
    perm_viewNotifications: "Voir les notifications",
    noNotifications: "Aucune notification",
    themeToggle: "Basculer mode clair/sombre",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    errorNoInventory: "Aucun article d'inventaire sélectionné.",
    inventoryDeleteConfirm: "Supprimer l'article ?",
    inventoryDeleteConfirmMsg: "Voulez-vous vraiment supprimer cet article d'inventaire ?",
    inventoryUpdateTitle: "Modifier l'article",
    inventoryReportIncident: "Signaler un incident",
    inventoryOnHand: "En stock",
    inventoryOnHandShort: "Qté",
    inventoryUnitValue: "Valeur unitaire",
    inventoryUnitValueShort: "Unit.",
    inventoryTotal: "Total",
    inventoryTotalShort: "Total",
    inventoryStatus: "Statut",
    inventoryExpiry: "Expiration",
    inventoryLastUpdated: "Dernière mise à jour",
    inventoryLastUpdatedShort: "Maj",
    inventoryExpiresOn: "Expire le",
    inventoryNotes: "Notes",
    inventoryImage: "Image de l'article",
    inventoryStoragePlace: "Emplacement de stockage",
    inventoryStoragePlaceShort: "Empl.",
    inventoryStoragePlaceHint: "Rayon, bac, chambre froide, zone…",
    inventorySiteLabel: "Site",
    inventoryImageUploadFailed: "Échec du téléversement de l'image.",
    inventoryChangeImage: "Changer l'image",
    inventorySearch: "Rechercher…",
    inventoryFilterStatus: "Statut",
    inventoryFilterType: "Type",
    inventoryFilterAll: "Tous",
    inventoryExpiringSoon: "Expire dans 30 jours",
    inventoryStatus_available: "Disponible",
    inventoryStatus_damaged: "Endommagé",
    inventoryStatus_expired: "Expiré",
    inventoryStatus_missing: "Manquant",
    inventoryReason_damaged: "Endommagé / cassé",
    inventoryReason_expired: "Expiré / périmé",
    inventoryReason_stolen: "Volé / manquant",
    inventoryReason_restored: "Restauré / retrouvé",
    inventoryReason_adjustment: "Ajustement de quantité",
    inventoryIncidentReason: "Motif",
    inventoryIncidentQty: "Quantité",
    inventoryIncidentNote: "Note",
    inventoryIncidentNoteRequired: "Une note est requise pour les incidents endommagé ou volé.",
    inventoryIncidentQtyInvalid: "Saisissez une quantité valide pour cet incident.",
    inventoryIncidentSuccess: "Incident enregistré.",
    inventoryIncidentFailed: "Échec de l'enregistrement de l'incident.",
    inventoryAdded: "Article d'inventaire ajouté",
    inventoryUpdated: "Article d'inventaire mis à jour",
    inventoryRemoved: "Article d'inventaire supprimé",
    inventoryNoPermAdd: "Vous n'avez pas la permission d'ajouter des articles.",
    inventoryNoPermUpdate: "Vous n'avez pas la permission de modifier l'inventaire.",
    inventoryNoPermDelete: "Vous n'avez pas la permission de supprimer des articles.",
    inventoryHealth: "Santé de l'inventaire",
    inventoryAvailableValue: "Valeur disponible",
    inventoryLossValue: "Valeur des pertes",
    inventoryUnitsLost: "Unités perdues",
    inventoryDamagedUnits: "Endommagé",
    inventoryExpiredUnits: "Expiré",
    inventoryStolenUnits: "Volé",
    inventoryExpiringSoonCount: "Expire bientôt",
    inventoryLossesByReason: "Pertes d'inventaire par motif",
    inventoryLossesSheet: "Pertes inventaire",
    inventoryNoItems: "Aucun article ne correspond aux filtres.",
    newHire: "Nouvelle embauche",
    staffTerminationDate: "Date de fin de contrat",
    staffDeleted: "Compte employé supprimé",
    incomeDeleted: "Revenu supprimé",
    expenseDeleted: "Dépense supprimée",
    inventoryDeleted: "Article d'inventaire supprimé",
    reportDownloaded: "Rapport téléchargé",
    newEstimate: "Nouveau devis",
    editEstimate: "Modifier le devis",
    estimateTitle: "Titre",
    estimateNumber: "N° devis",
    estimateStatus: "Statut",
    estimateCustomer: "Client",
    estimateBusiness: "Entreprise",
    estimateLineItems: "Lignes",
    estimatePreview: "Aperçu",
    estimateTemplate: "Modèle",
    estimateIndustryTemplates: "Modèles métiers",
    estimateUserTemplates: "Vos modèles",
    archiveAsTemplate: "Archiver comme modèle",
    estimateLogo: "Logo",
    primaryColor: "Couleur principale",
    accentColor: "Couleur d'accent",
    estimateLayout: "Mise en page",
    layoutClassic: "Classique",
    layoutModern: "Moderne",
    layoutCompact: "Compacte",
    validUntil: "Valable jusqu'au",
    issueDate: "Date d'émission",
    taxRate: "Taxe %",
    subtotal: "Sous-total",
    taxAmount: "Taxe",
    total: "Total",
    unitPrice: "Prix unitaire",
    unit: "Unité",
    lineTotal: "Total ligne",
    terms: "Conditions",
    notes: "Notes",
    exportCsv: "Exporter CSV",
    exportExcel: "Exporter Excel",
    exportPdf: "Imprimer / PDF",
    copyPlainText: "Copier le texte",
    estimateDraft: "Brouillon",
    estimateSent: "Envoyé",
    estimateAccepted: "Accepté",
    estimateRejected: "Refusé",
    estimateArchived: "Archivé",
    noEstimates: "Aucun devis pour le moment.",
    searchEstimates: "Rechercher des devis…",
    addLineItem: "Ajouter une ligne",
    removeLineItem: "Retirer",
    customerName: "Nom du client",
    customerEmail: "Email client",
    customerPhone: "Téléphone client",
    customerAddress: "Adresse client",
    businessName: "Nom de l'entreprise",
    businessAddress: "Adresse de l'entreprise",
    businessPhone: "Téléphone de l'entreprise",
    estimateSaved: "Devis enregistré",
    estimateDeleted: "Devis supprimé",
    templateArchived: "Enregistré comme modèle",
    pickTemplate: "Partir d'un modèle",
    blankEstimate: "Devis vierge",
    // Marketing / Navigation
    navDescription: "Description",
    navPartners: "Nos partenaires",
    navFeatures: "Fonctionnalités",
    navTestimonials: "Témoignages",
    navFaq: "FAQ",
    navBlog: "Blog",
    getStarted: "Commencer",
    getItNow: "Obtenez-le maintenant",
    trustedBy: "Approuvé par les meilleures entreprises",

    // Hero
    heroTitle: "Votre&nbsp;nouveau&nbsp;compagnon&nbsp;d'affaires&nbsp;",
    heroHighlight: "SMARTER&nbsp;PANEL",
    heroSubtitle:
      "SMARTER PANEL est un tableau de bord de gestion RH et comptable complet pour les opérations commerciales. Fonctionnalités : suivi des revenus/dépenses, gestion des stocks, administration du personnel et rapports financiers.",

    // Highlights
    highlightsTitle: "Points forts",
    highlightsDesc:
      "Découvrez pourquoi notre produit se démarque : adaptabilité, durabilité, conception conviviale et innovation. Profitez d'un support client fiable et d'une précision dans chaque détail.",
    highlightAdaptableTitle: "Performance adaptable",
    highlightAdaptableDesc:
      "Notre produit s'adapte facilement à vos besoins, augmentant l'efficacité et simplifiant vos tâches.",
    highlightBuiltToLastTitle: "Conçu pour durer",
    highlightBuiltToLastDesc:
      "Vivez une durabilité inégalée qui va au-delà avec un investissement durable.",
    highlightUserExperienceTitle: "Excellente expérience utilisateur",
    highlightUserExperienceDesc:
      "Intégrez notre produit dans votre routine avec une interface intuitive et facile à utiliser.",
    highlightInnovativeTitle: "Fonctionnalité innovante",
    highlightInnovativeDesc:
      "Gardez une longueur d'avance avec des fonctionnalités qui établissent de nouvelles normes, répondant mieux à vos besoins évolutifs.",
    highlightSupportTitle: "Support fiable",
    highlightSupportDesc:
      "Comptez sur notre service client réactif, offrant une assistance qui va au-delà de l'achat.",
    highlightPrecisionTitle: "Précision dans chaque détail",
    highlightPrecisionDesc:
      "Profitez d'un produit méticuleusement conçu où les petites touches ont un impact significatif sur votre expérience globale.",

    // Features
    featuresTitle: "Fonctionnalités du produit",
    featuresDesc:
      "Donnez un aperçu des principales fonctionnalités du produit. Par exemple, vous pouvez lister le nombre de fonctionnalités, leurs types ou avantages, et les ajouts.",
    featureDashboardTitle: "Vue d'ensemble du tableau de bord, finances, RH, opérations et plus encore",
    featureDashboardDesc:
      "Notre solution donne aux utilisateurs un accès facile à des outils pour gérer leur activité, des finances aux opérations, le tout en un seul endroit.",
    featureOfflineTitle: "Intégration de la fonctionnalité hors ligne",
    featureOfflineDesc:
      "Notre produit pourrait fournir une fonctionnalité hors ligne, permettant aux utilisateurs de continuer à travailler même lorsqu'ils ne sont pas connectés à Internet.",
    featureDevicesTitle: "Disponible sur tous les appareils",
    featureDevicesDesc:
      "Cet élément permet aux utilisateurs de savoir que le produit est disponible sur toutes les plateformes, telles que le web, mobile et bureau.",

    // Testimonials
    testimonialsTitle: "Témoignages",
    testimonialsDesc:
      "Découvrez ce que nos clients aiment à propos de nos produits. Découvrez comment nous excellons en matière d'efficacité, de durabilité et de satisfaction. Rejoignez-nous pour la qualité, l'innovation et un support fiable.",
    testimonial1Name: "Remy Sharp",
    testimonial1Occupation: "Ingénieur senior",
    testimonial1Text:
      "J'adore la polyvalence de ce produit ! Que je m'attaque à des projets professionnels ou à mes loisirs préférés, il s'adapte parfaitement à mes besoins changeants. Sa conception intuitive a vraiment amélioré ma routine quotidienne, rendant les tâches plus efficaces et agréables.",
    testimonial2Name: "Travis Howard",
    testimonial2Occupation: "Lead Product Designer",
    testimonial2Text:
      "L'une des caractéristiques remarquables de ce produit est le support client exceptionnel. D'après mon expérience, l'équipe derrière ce produit a été rapide à répondre et incroyablement utile. C'est rassurant de savoir qu'ils soutiennent fermement leur produit.",
    testimonial3Name: "Cindy Baker",
    testimonial3Occupation: "CTO",
    testimonial3Text:
      "Le niveau de simplicité et de convivialité de ce produit a considérablement simplifié ma vie. J'apprécie les créateurs pour avoir livré une solution qui répond non seulement mais dépasse les attentes des utilisateurs.",
    testimonial4Name: "Julia Stewart",
    testimonial4Occupation: "Ingénieur senior",
    testimonial4Text:
      "J'apprécie l'attention portée aux détails dans la conception de ce produit. Les petites touches font une grande différence, et il est évident que les créateurs se sont concentrés sur la fourniture d'une expérience premium.",
    testimonial5Name: "John Smith",
    testimonial5Occupation: "Product Designer",
    testimonial5Text:
      "J'ai essayé d'autres produits similaires, mais celui-ci se démarque par ses fonctionnalités innovantes. Il est clair que les fabricants ont mis beaucoup de réflexion dans la création d'une solution qui répond vraiment aux besoins des utilisateurs.",
    testimonial6Name: "Daniel Wolf",
    testimonial6Occupation: "CDO",
    testimonial6Text:
      "La qualité de ce produit a dépassé mes attentes. Il est durable, bien conçu et construit pour durer. Cela vaut vraiment l'investissement !",

    // Pricing
    pricingTitle: "Tarifs",
    pricingDesc: "Choisissez le forfait qui vous convient, à vous et à votre équipe.",
    planFreeTitle: "Gratuit",
    // planFreeDescription: ["1 utilisateur inclus", "1 site inclus", "Stockage illimité", "Téléchargement de rapports", "Assistance par e-mail", "Support client 24/7"],
    planStarterTitle: "Démarrage",
    // planStarterDescription: ["2 utilisateurs inclus", "2 sites inclus", "Stockage illimité", "Accès au centre d'aide", "Téléchargement de rapports", "Assistance par e-mail", "Support client 24/7"],
    planGrowthTitle: "Croissance",
    // planGrowthDescription: ["5 utilisateurs inclus", "3 sites inclus", "Stockage illimité", "Téléchargement de rapports", "Accès au centre d'aide", "Assistance e-mail prioritaire", "Meilleures offres", "Support client 24/7"],
    planEnterpriseTitle: "Entreprise",
    // planEnterpriseDescription: ["Utilisateurs illimités", "Sites illimités", "Stockage illimité", "Accès prioritaire au centre d'aide", "Équipe dédiée", "Téléchargement de rapports", "Assistance téléphonique et e-mail", "Assistance e-mail prioritaire", "Support client 24/7"],
    // In TRANSLATIONS.fr
    planFreeDescription: "1 utilisateur inclus\n1 site inclus\nStockage illimité\nTéléchargement de rapports\nAssistance par e-mail\nSupport client 24/7",
    planStarterDescription: "2 utilisateurs inclus\n2 sites inclus\nStockage illimité\nAccès au centre d'aide\nTéléchargement de rapports\nAssistance par e-mail\nSupport client 24/7",
    planGrowthDescription: "5 utilisateurs inclus\n3 sites inclus\nStockage illimité\nTéléchargement de rapports\nAccès au centre d'aide\nAssistance e-mail prioritaire\nMeilleures offres\nSupport client 24/7",
    planEnterpriseDescription: "Utilisateurs illimités\nSites illimités\nStockage illimité\nAccès prioritaire au centre d'aide\nÉquipe dédiée\nTéléchargement de rapports\nAssistance téléphonique et e-mail\nAssistance e-mail prioritaire\nSupport client 24/7",
    planFreeButton: "S'inscrire gratuitement",
    planStarterButton: "Commencer",
    planGrowthButton: "Commencer maintenant",
    planEnterpriseButton: "Devenir plus intelligent",
    perMonth: "/ mois",

    // FAQ
    faqTitle: "Questions fréquemment posées",
    faqQuestion1: "Comment se connecter ? Quel est le flux OTP ?",
    faqAnswer1:
      "Connectez-vous avec votre e-mail et votre mot de passe, puis vérifiez à l'aide du code unique envoyé à votre e-mail. Utilisez le bouton <strong>Renvoyer le code</strong> si le code n'arrive pas. L'application utilise l'OTP par e-mail plutôt qu'une authentification par mot de passe seul pour une sécurité accrue.",
    faqQuestion2: "Je n'ai pas reçu d'OTP ou d'e-mail d'invitation — que dois-je faire ?",
    faqAnswer2:
      "Vérifiez votre dossier spam/courrier indésirable et confirmez que l'e-mail est correct. Demandez à l'expéditeur de renvoyer l'invitation ou le code. Si l'application affiche des erreurs SMTP ou de livraison, contactez le support ou l'administrateur de votre organisation.",
    faqQuestion3: "Comment fonctionnent le mode hors ligne et la synchronisation ?",
    faqAnswer3:
      "La PWA peut mettre en file d'attente certaines créations, mises à jour et téléchargements dans le navigateur (IndexedDB) en mode hors ligne. Lorsque vous vous reconnectez, les actions en file d'attente sont synchronisées avec le serveur. Évitez d'effacer les données du site jusqu'à ce que la synchronisation soit terminée pour éviter la perte de données.",
    faqQuestion4: "Où puis-je trouver la politique de confidentialité et les conditions ? Comment demander la suppression des données ?",
    faqAnswer4:
      "Les liens vers la politique de confidentialité et les conditions sont disponibles dans le pied de page et dans le centre d'aide. Pour les demandes d'exportation ou de suppression de données, contactez le contact de confidentialité indiqué sur la page de politique de confidentialité (ou envoyez un e-mail au propriétaire/administrateur de l'organisation pour lancer la demande).",

    // Footer
    footerDescription: "Smarter Panel est une plateforme puissante et conviviale qui aide les entreprises à rationaliser leurs opérations.",
    footerProduct: "Produit",
    footerDescriptionLink: "Description",
    footerFeaturesLink: "Fonctionnalités",
    footerTestimonialsLink: "Témoignages",
    footerPricingLink: "Tarifs",
    footerHelpCenter: "Centre d'aide",
    footerFaq: "FAQ",
    footerCompany: "Entreprise",
    footerAboutUs: "À propos de nous",
    footerCareers: "Carrières",
    footerPress: "Presse",
    footerPrivacyPolicy: "Politique de confidentialité",
    footerTermsOfService: "Conditions d'utilisation",
    footerCopyright: "Copyright © {year} Smarter Panel",
    and: "et les",

    // In TRANSLATIONS.fr
    helpTitle: "Centre d'aide — Smarter Panel",
    helpIntro: "Guide pratique d'utilisation de Smarter Panel. Vous trouverez ci-dessous des sujets pour vous aider à démarrer, résoudre les problèmes courants et comprendre les limites et règles du produit. Pour les conditions de confidentialité et légales, consultez les liens en bas de page.",
    helpGettingStartedTitle: "Premiers pas",
    helpGettingStartedText: "Créez une organisation depuis l'écran de connexion, définissez un mot de passe (6 caractères min.) et vérifiez à l'aide du code envoyé à votre e-mail. Complétez les profils d'organisation et personnel comme demandé.",
    helpSignInTitle: "Connexion, OTP et réinitialisation du mot de passe",
    helpSignInText: "Smarter Panel utilise des codes à usage unique (OTP) par e-mail pour la connexion, l'inscription et la réinitialisation du mot de passe. Si vous ne recevez pas de code, vérifiez les spams/courriers indésirables et utilisez le bouton de renvoi. Dans les environnements de développement, un OTP de développement peut être affiché à l'écran lorsque SMTP n'est pas configuré.",
    helpInvitationsTitle: "Invitations",
    helpInvitationsText: "Les administrateurs invitent des utilisateurs depuis Admin → Utilisateurs. Les invités acceptent via le lien ou le jeton dans l'e-mail, définissent un mot de passe, puis vérifient à l'aide d'un code e-mail.",
    helpOfflineTitle: "Mode hors ligne",
    helpOfflineText: "La PWA prend en charge les files d'attente hors ligne pour certaines créations/mises à jour/téléchargements. Si vous travaillez hors ligne, les éléments sont mis en file d'attente dans le navigateur (IndexedDB) et synchronisés lorsque la connectivité revient. L'effacement des données du site peut supprimer le travail non synchronisé.",
    helpSupportTitle: "Support",
    helpSupportText: "Utilisez le chat de support flottant dans l'application ou envoyez un e-mail à notre équipe de support à {email}.",
    helpDocLink: "Pour la documentation complète, consultez la ",

    privacyTitle: "Politique de confidentialité — Smarter Panel",
    privacyIntro: "Cette page résume comment Smarter Panel collecte et traite les données. Ceci est un brouillon orienté produit — faites-le réviser par un juriste avant la mise en production.",
    privacyWhatCollectTitle: "Ce que nous collectons",
    privacyWhatCollectText: "Nous collectons les données de compte/profil, les données d'organisation, les données opérationnelles de l'entreprise (revenus, dépenses, stocks, RH), les communications de facturation et de support, les données d'authentification (OTP et jetons) et les caches côté client pour le support hors ligne.",
    privacyWhyProcessTitle: "Pourquoi nous traitons les données",
    privacyWhyProcessText: "Pour fournir et sécuriser le Service, soutenir l'intégration, la facturation, la continuité hors ligne et la conformité légale. Nous ne vendons pas vos informations personnelles.",
    privacySharingTitle: "Partage",
    privacySharingText: "Nous partageons les données avec votre organisation, notre processeur de paiement, nos fournisseurs d'e-mail, notre infrastructure d'hébergement et lorsque la loi l'exige.",
    privacyRetentionTitle: "Conservation et suppression",
    privacyRetentionText: "Les données actives sont conservées pendant que votre organisation utilise le Service. Les caches des appareils persistent jusqu'à leur effacement. Contactez la confidentialité pour les demandes d'exportation ou de suppression.",
    privacyContact: "Contact : {email}",

    termsTitle: "Conditions générales — Smarter Panel",
    termsIntro: "Ces conditions régissent l'accès et l'utilisation de Smarter Panel. Ceci est un brouillon de produit et doit être révisé par un juriste avant publication.",
    termsAccountsTitle: "Comptes et éligibilité",
    termsAccountsText: "Les organisations et les comptes propriétaires sont responsables des profils, des utilisateurs, des abonnements et du respect de ces conditions.",
    termsSubscriptionsTitle: "Abonnements et facturation",
    termsSubscriptionsText: "Les forfaits peuvent limiter les utilisateurs et les sites. Les propriétaires gèrent la facturation et peuvent mettre à niveau ou renouveler via l'interface de facturation. Le paiement peut utiliser un fournisseur tiers.",
    termsRulesTitle: "Règles du produit",
    termsRulesText: "Le produit applique des règles pratiques telles que des limites de date de 7 jours et des verrous de modification/suppression de 24 heures sur de nombreux enregistrements pour réduire la fraude et les erreurs.",
    termsContact: "Contact légal : {email}",
  }
};

export const formatCurrency = (
  amount: number,
  displayCode: string,
  fromCode?: string,
  rates?: Record<string, number> | null
) => {
  const currency = CURRENCIES[(displayCode as CurrencyCode)] || CURRENCIES.XAF;
  const from = fromCode || displayCode;
  const converted = convertAmount(amount, from, currency.code, rates);
  return new Intl.NumberFormat('fr-FR', {
    style: 'currency',
    currency: currency.code,
    maximumFractionDigits: currency.precision,
    minimumFractionDigits: currency.precision,
  }).format(converted);
};

export const getTranslated = (item: any, lang: string) => {
  if (!item) return '';
  return item[lang] || item['en'] || 'N/A';
};

/** Fraud prevention: records older than 24 hours cannot be edited or deleted (applies to income, expense, inventory registration delete/edit). */
export const isLockedAfter24Hours = (createdAt: string | Date | undefined): boolean => {
  if (!createdAt) return false;
  const created = typeof createdAt === 'string' ? new Date(createdAt) : createdAt;
  return Date.now() - created.getTime() > 24 * 60 * 60 * 1000;
};

const LOSS_REASONS: InventoryEventReason[] = ['damaged', 'expired', 'stolen'];

export const isInventoryLossReason = (reason: InventoryEventReason) => LOSS_REASONS.includes(reason);

export const isExpiringSoon = (expiresOn: string | null | undefined, withinDays = 30): boolean => {
  if (!expiresOn) return false;
  const exp = new Date(expiresOn);
  if (Number.isNaN(exp.getTime())) return false;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const limit = new Date(today);
  limit.setDate(limit.getDate() + withinDays);
  return exp >= today && exp <= limit;
};

export const isPastExpiry = (expiresOn: string | null | undefined): boolean => {
  if (!expiresOn) return false;
  const exp = new Date(expiresOn);
  if (Number.isNaN(exp.getTime())) return false;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return exp < today;
};

/** Display status for an inventory line (on-hand + expiry + last stored status). */
export const deriveInventoryStatus = (item: Pick<InventoryItem, 'quantity' | 'status' | 'expiresOn'>): InventoryStatus => {
  if (isPastExpiry(item.expiresOn)) return 'expired';
  if ((item.quantity ?? 0) <= 0) {
    if (item.status === 'damaged' || item.status === 'expired' || item.status === 'missing') return item.status;
    return 'missing';
  }
  if (item.status === 'damaged') return 'damaged';
  return 'available';
};

/** Next status after applying an incident that changes on-hand quantity. */
export const statusAfterIncident = (
  reason: InventoryEventReason,
  nextQty: number,
  expiresOn?: string | null
): InventoryStatus => {
  if (isPastExpiry(expiresOn)) return 'expired';
  if (nextQty <= 0) {
    if (reason === 'stolen') return 'missing';
    if (reason === 'damaged') return 'damaged';
    if (reason === 'expired') return 'expired';
    return 'missing';
  }
  if (reason === 'damaged') return 'damaged';
  return 'available';
};

// Helper for 7-day rule
export const isDateWithinLimit = (dateString: string) => {
  const inputDate = new Date(dateString);
  const today = new Date();
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(today.getDate() - 7);

  // Reset hours to compare dates only
  inputDate.setHours(0, 0, 0, 0);
  today.setHours(0, 0, 0, 0);
  sevenDaysAgo.setHours(0, 0, 0, 0);

  return inputDate >= sevenDaysAgo && inputDate <= today;
};