
import type { InventoryEventReason, InventoryItem, InventoryStatus } from './types';

export const CURRENCIES = {
  XAF: { code: 'XAF', rate: 1, symbol: 'FCFA', precision: 0 },
  USD: { code: 'USD', rate: 0.00165, symbol: '$ US', precision: 2 },
  CAD: { code: 'CAD', rate: 0.00225, symbol: '$ CAD', precision: 2 },
  EUR: { code: 'EUR', rate: 0.00152, symbol: '€', precision: 2 },
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    loginWelcome: "Smarter Panel",
    loginToAccess: "Login to access your dashboard.",
    login: "Login",
    email: "Email",
    password: "Password",
    signupTitle: "Create your organization",
    signupSubtitle: "Start free with one user and one location. Complete your profile after signup.",
    otpTitle: "Enter verification code",
    otpSubtitle: "We sent a one-time code to your email.",
    inviteTitle: "Accept invitation",
    inviteSubtitle: "Set your password to join the organization.",
    organizationName: "Organization name",
    createOrganization: "Create an organization",
    createAccount: "Create account",
    noAccount: "New here?",
    haveAccount: "Already have an account?",
    pleaseWait: "Please wait…",
    otpCode: "Verification code",
    verifyOtp: "Verify",
    resendOtp: "Resend code",
    inviteToken: "Invite token",
    acceptInvite: "Continue",
    backToLogin: "Back to login",
    forgotPassword: "Forgot password?",
    forgotPasswordTitle: "Reset your password",
    forgotPasswordSubtitle: "Enter your email and we’ll send a verification code.",
    forgotResetTitle: "Choose a new password",
    forgotResetSubtitle: "Enter the code from your email and your new password.",
    sendResetCode: "Send reset code",
    resetPasswordSubmit: "Update password",
    forgotSuccess: "Password updated. You can log in with your new password.",
    devOtpHint: "Dev OTP (SMTP not configured)",
    orgProfileTitle: "Complete organization profile",
    orgProfileSubtitle: "Business details for your organization. Separate from your personal profile.",
    legalName: "Legal name",
    taxId: "Tax ID",
    saveOrgProfile: "Save organization profile",
    orgProfileSaved: "Organization profile saved",
    orgLogoHint: "Upload your organization logo (optional).",
    orgSectionIdentity: "Identity",
    orgSectionContact: "Contact",
    orgSectionAddress: "Address",
    industry: "Industry",
    orgDescription: "About the organization",
    orgEmail: "Organization email",
    city: "City",
    country: "Country",
    postalCode: "Postal code",
    website: "Website",
    organization: "Organization",
    personalProfileTitle: "Complete your personal profile",
    personalProfileSubtitle: "Your personal details within this organization.",
    personalProfileSaved: "Personal profile saved",
    personalInfo: "Personal information",
    jobTitle: "Job title",
    owner: "Owner",
    billing: "Billing",
    billingSubtitle: "Manage your subscription plan and renewals.",
    currentPlan: "Current plan",
    plan: "Plan",
    dueDate: "Due date",
    choosePlan: "Choose a plan",
    subscribe: "Subscribe",
    unlimitedUsers: "Unlimited users",
    unlimitedLocations: "Unlimited locations",
    couponCode: "Coupon code",
    applyCoupon: "Apply",
    assignedCoupons: "Assigned to your org",
    couponApplied: "Coupon applied",
    couponInvalid: "Invalid coupon code",
    couponCheckoutActivated: "Subscription activated with your coupon — no payment required.",
    renewalWindowHint: "You can renew or change plans only within 5 days before or after your due date.",
    probationBanner: "Your organization is on free-tier probation. Only the owner can sign in until you subscribe again.",
    paymentSimulated: "Payment marked successful (dev).",
    sendInvite: "Send invite",
    inviteEmailHint: "Invite a teammate by email. They will receive a link, set their password, and verify with OTP.",
    inviteSent: "Invitation sent",
    inviteResent: "Invitation resent",
    inviteEmailFailed: "Email could not be sent — check SMTP or resend later",
    pendingInvites: "Pending invitations",
    resendInvite: "Resend",
    inviteFromStaff: "Invite from staff",
    dashboard: "Dashboard",
    income: "Income",
    expenses: "Expenses",
    inventory: "Inventory",
    hr: "HR",
    reports: "Reports",
    estimates: "Estimates",
    admin: "Admin",
    logout: "Logout",
    totalIncome: "Total Income",
    totalExpenses: "Total Expenses",
    netBalance: "Net Balance",
    inventoryValue: "Inventory Value",
    recentActivity: "Recent Activity",
    add: "Add",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    editUser: "Edit user",
    saveChanges: "Save changes",
    actions: "Actions",
    source: "Source",
    amount: "Amount",
    date: "Date",
    description: "Description",
    category: "Category",
    item: "Item",
    type: "Type",
    quantity: "Quantity",
    value: "Value",
    firstName: "First Name",
    lastName: "Last Name",
    position: "Position",
    status: "Status",
    documents: "Documents",
    upload: "Upload",
    download: "Download",
    view: "View",
    back: "Back",
    profile: "My Profile",
    address: "Address",
    phone: "Phone",
    gender: "Gender",
    dob: "Date of Birth",
    hireDate: "Hire Date",
    terminationDate: "Termination Date",
    allLocations: "All Locations",
    selectLocation: "Select Location",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    passwordMismatch: "Passwords do not match.",
    passwordChanged: "Password changed successfully.",
    resetPassword: "Reset Password",
    resetSuccess: "Password reset. Temp password: ",
    oldPassword: "Current Password",
    oldPasswordRequired: "Current password is required",
    confirmDelete: "Confirm Delete",
    deactivate: "Deactivate",
    reactivate: "Reactivate",
    remove: "Remove",
    confirmDeactivateUser: "Deactivate this user? They will no longer be able to log in.",
    confirmRemoveUser: "Permanently remove this user? This cannot be undone.",
    userDeactivated: "User deactivated",
    userReactivated: "User reactivated",
    userRemoved: "User removed",
    active: "Active",
    inactive: "Inactive",
    deleteStaffConfirm: "Are you sure you want to delete this staff member?",
    noUserAccount: "This staff member has no user account",
    uploadDocument: "Upload Document",
    documentName: "Document Name",
    documentType: "Document Type",
    selectFile: "Select File",
    updatePermissions: "Update Permissions",
    positions: "Positions",
    noDocuments: "No documents uploaded yet",
    permissionsSelected: "permissions selected",
    perm_viewDashboard: "View Dashboard",
    perm_viewIncome: "View Income",
    perm_addIncome: "Add Income",
    perm_deleteIncome: "Delete Income",
    perm_viewExpenses: "View Expenses",
    perm_addExpenses: "Add Expenses",
    perm_deleteExpenses: "Delete Expenses",
    perm_manageCategories: "Manage Categories",
    perm_viewInventory: "View Inventory",
    perm_addInventory: "Add Inventory",
    perm_updateInventory: "Update Inventory / Report Incidents",
    perm_deleteInventory: "Delete Inventory",
    perm_manageTypes: "Manage Inventory Types",
    perm_viewHR: "View HR",
    perm_addHR: "Add Employee",
    perm_updateHR: "Update Employee",
    perm_deleteHR: "Delete Employee",
    perm_manageHRUploads: "Manage HR Documents",
    perm_managePositions: "Manage Positions",
    perm_manageDocs: "Manage Documents",
    perm_viewReports: "View Reports",
    perm_viewEstimates: "View Estimates",
    perm_addEstimates: "Add Estimates",
    perm_updateEstimates: "Update Estimates",
    perm_deleteEstimates: "Delete Estimates",
    perm_manageEstimateTemplates: "Manage Estimate Templates",
    perm_viewAdmin: "Admin Access",
    perm_manageAdminUsers: "Admin: User Management tab",
    perm_manageAdminRoles: "Admin: Role Management tab",
    perm_manageAdminConfig: "Admin: Config (locations, categories, types, positions, sources, descriptions, storage places)",
    adminNoSubPermission: "You don't have permission to manage any settings. Contact an administrator to get access to User Management, Role Management, or Config.",
    perm_allLocations: "All Locations Access",
    manage_users: "Manage Users (create, edit, delete, reset password for any user)",
    perm_resetUserPassword: "Reset User Password (users in your location only)",
    perm_deactivateUser: "Deactivate users",
    perm_removeUser: "Remove users",
    errorFillFields: "Please fill all required fields.",
    errorDateFuture: "Date cannot be in the future.",
    errorDatePast: "Date cannot be older than 7 days.",
    errorNoLocation: "Please select a specific location.",
    userManagement: "User Management",
    roleManagement: "Role Management",
    locationManagement: "Locations",
    configManagement: "Configurations",
    generateReport: "Generate Report",
    forecast: "Financial Forecast",
    monthly: "Monthly",
    quarterly: "Quarterly",
    yearly: "Yearly",
    allTime: "All Time",
    dateRange: "Date Range",
    dateFrom: "From",
    dateTo: "To",
    last7Days: "Last 7 days",
    thisMonth: "This month",
    thisYear: "This year",
    last12Months: "Last 12 months",
    incomeVsExpenses: "Income vs Expenses",
    incomeBySource: "Income by Source",
    expensesByCategory: "Expenses by Category",
    financialOverview: "Financial Overview",
    financialHealth: "Financial Health",
    netTrend: "Net Balance Trend",
    showCharts: "Show charts",
    hideCharts: "Hide charts",
    downloadCSV: "Download CSV",
    downloadExcel: "Download Excel",
    forecastTitle: "Projected Financials",
    forecastDesc: "Based on historical average",
    managePermissions: "Manage Permissions",
    roleName: "Role Name",
    permissions: "Permissions",
    expenseCategories: "Expense Categories",
    inventoryTypes: "Inventory Types",
    incomeSources: "Income Sources",
    expenseDescriptions: "Expense Descriptions",
    storagePlaces: "Storage Places",
    name: "Name",
    nameFr: "Name (FR)",
    metric: "Metric",
    allMetrics: "All Metrics",
    incomeOnly: "Income Only",
    expensesOnly: "Expenses Only",
    inventoryOnly: "Inventory",
    specificLocation: "Specific Location",
    changePhoto: "Change Photo",
    updateProfile: "Update Profile",
    mandatoryReset: "Security Alert: You must change your password to continue.",
    hierarchyForbidden: "You cannot modify or delete a user who is above you in the hierarchy.",
    locked24hMessage: "Cannot modify or delete after 24 hours (fraud prevention).",
    auditLogs: "Audit Logs",
    perm_viewAuditLogs: "View Audit Logs",
    filterByLocation: "Location",
    filterByUser: "User",
    searchByName: "Search by name",
    filterByPosition: "Position",
    allPositions: "All positions",
    listView: "List view",
    gridView: "Grid view",
    auditAction: "Action",
    auditResource: "Resource",
    auditTime: "Time",
    auditDetails: "Details",
    auditUser: "User",
    auditLocation: "Location",
    noAuditLogs: "No audit logs found.",
    applyFilters: "Apply",
    clearFilters: "Clear",
    notifications: "Notifications",
    perm_viewNotifications: "View Notifications",
    noNotifications: "No notifications",
    themeToggle: "Toggle light/dark mode",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    errorNoInventory: "No inventory item selected.",
    inventoryDeleteConfirm: "Delete inventory item?",
    inventoryDeleteConfirmMsg: "Are you sure you want to delete this inventory item?",
    inventoryUpdateTitle: "Edit inventory item",
    inventoryReportIncident: "Report incident",
    inventoryOnHand: "On hand",
    inventoryOnHandShort: "Qty",
    inventoryUnitValue: "Unit value",
    inventoryUnitValueShort: "Unit",
    inventoryTotal: "Total",
    inventoryTotalShort: "Total",
    inventoryStatus: "Status",
    inventoryExpiry: "Expiry",
    inventoryLastUpdated: "Last updated",
    inventoryLastUpdatedShort: "Updated",
    inventoryExpiresOn: "Expires on",
    inventoryNotes: "Notes",
    inventoryImage: "Item image",
    inventoryStoragePlace: "Storage place",
    inventoryStoragePlaceShort: "Place",
    inventoryStoragePlaceHint: "Shelf, bin, cold room, zone…",
    inventorySiteLabel: "Business site",
    inventoryImageUploadFailed: "Failed to upload item image.",
    inventoryChangeImage: "Change image",
    inventorySearch: "Search items…",
    inventoryFilterStatus: "Status",
    inventoryFilterType: "Type",
    inventoryFilterAll: "All",
    inventoryExpiringSoon: "Expiring within 30 days",
    inventoryStatus_available: "Available",
    inventoryStatus_damaged: "Damaged",
    inventoryStatus_expired: "Expired",
    inventoryStatus_missing: "Missing",
    inventoryReason_damaged: "Damaged / broken",
    inventoryReason_expired: "Expired / spoiled",
    inventoryReason_stolen: "Stolen / missing",
    inventoryReason_restored: "Restored / found",
    inventoryReason_adjustment: "Quantity adjustment",
    inventoryIncidentReason: "Reason",
    inventoryIncidentQty: "Quantity",
    inventoryIncidentNote: "Note",
    inventoryIncidentNoteRequired: "A note is required for damaged or stolen incidents.",
    inventoryIncidentQtyInvalid: "Enter a valid quantity for this incident.",
    inventoryIncidentSuccess: "Incident recorded.",
    inventoryIncidentFailed: "Failed to record incident.",
    inventoryAdded: "Inventory item added successfully",
    inventoryUpdated: "Inventory item updated successfully",
    inventoryRemoved: "Inventory item removed successfully",
    inventoryNoPermAdd: "You do not have permission to add inventory items.",
    inventoryNoPermUpdate: "You do not have permission to update inventory.",
    inventoryNoPermDelete: "You do not have permission to delete inventory items.",
    inventoryHealth: "Inventory health",
    inventoryAvailableValue: "Available value",
    inventoryLossValue: "Loss value",
    inventoryUnitsLost: "Units lost",
    inventoryDamagedUnits: "Damaged",
    inventoryExpiredUnits: "Expired",
    inventoryStolenUnits: "Stolen",
    inventoryExpiringSoonCount: "Expiring soon",
    inventoryLossesByReason: "Inventory losses by reason",
    inventoryLossesSheet: "Inventory Losses",
    inventoryNoItems: "No inventory items match your filters.",
    newHire: "New hire",
    staffTerminationDate: "Termination date set",
    staffDeleted: "Staff account deleted",
    incomeDeleted: "Income deleted",
    expenseDeleted: "Expense deleted",
    inventoryDeleted: "Inventory item deleted",
    reportDownloaded: "Report downloaded",
    newEstimate: "New estimate",
    editEstimate: "Edit estimate",
    estimateTitle: "Title",
    estimateNumber: "Estimate #",
    estimateStatus: "Status",
    estimateCustomer: "Customer",
    estimateBusiness: "Business",
    estimateLineItems: "Line items",
    estimatePreview: "Preview",
    estimateTemplate: "Template",
    estimateIndustryTemplates: "Industry templates",
    estimateUserTemplates: "Your templates",
    archiveAsTemplate: "Archive as template",
    estimateLogo: "Logo",
    primaryColor: "Primary color",
    accentColor: "Accent color",
    estimateLayout: "Layout",
    layoutClassic: "Classic",
    layoutModern: "Modern",
    layoutCompact: "Compact",
    validUntil: "Valid until",
    issueDate: "Issue date",
    taxRate: "Tax %",
    subtotal: "Subtotal",
    taxAmount: "Tax",
    total: "Total",
    unitPrice: "Unit price",
    unit: "Unit",
    lineTotal: "Line total",
    terms: "Terms",
    notes: "Notes",
    exportCsv: "Export CSV",
    exportExcel: "Export Excel",
    exportPdf: "Print / PDF",
    copyPlainText: "Copy text",
    estimateDraft: "Draft",
    estimateSent: "Sent",
    estimateAccepted: "Accepted",
    estimateRejected: "Rejected",
    estimateArchived: "Archived",
    noEstimates: "No estimates yet.",
    searchEstimates: "Search estimates…",
    addLineItem: "Add line",
    removeLineItem: "Remove",
    customerName: "Customer name",
    customerEmail: "Customer email",
    customerPhone: "Customer phone",
    customerAddress: "Customer address",
    businessName: "Business name",
    businessAddress: "Business address",
    businessPhone: "Business phone",
    estimateSaved: "Estimate saved",
    estimateDeleted: "Estimate deleted",
    templateArchived: "Saved as template",
    pickTemplate: "Start from template",
    blankEstimate: "Blank estimate",
  },
  fr: {
    loginWelcome: "Smarter Panel",
    loginToAccess: "Connectez-vous pour accéder.",
    login: "Connexion",
    email: "Email",
    password: "Mot de passe",
    signupTitle: "Créer votre organisation",
    signupSubtitle: "Commencez gratuitement avec un utilisateur et un site. Complétez le profil après l'inscription.",
    otpTitle: "Code de vérification",
    otpSubtitle: "Nous avons envoyé un code unique à votre e-mail.",
    inviteTitle: "Accepter l'invitation",
    inviteSubtitle: "Définissez votre mot de passe pour rejoindre l'organisation.",
    organizationName: "Nom de l'organisation",
    createOrganization: "Créer une organisation",
    createAccount: "Créer le compte",
    noAccount: "Nouveau ?",
    haveAccount: "Déjà un compte ?",
    pleaseWait: "Veuillez patienter…",
    otpCode: "Code de vérification",
    verifyOtp: "Vérifier",
    resendOtp: "Renvoyer le code",
    inviteToken: "Jeton d'invitation",
    acceptInvite: "Continuer",
    backToLogin: "Retour à la connexion",
    forgotPassword: "Mot de passe oublié ?",
    forgotPasswordTitle: "Réinitialiser le mot de passe",
    forgotPasswordSubtitle: "Saisissez votre e-mail et nous enverrons un code de vérification.",
    forgotResetTitle: "Choisir un nouveau mot de passe",
    forgotResetSubtitle: "Entrez le code reçu par e-mail et votre nouveau mot de passe.",
    sendResetCode: "Envoyer le code",
    resetPasswordSubmit: "Mettre à jour le mot de passe",
    forgotSuccess: "Mot de passe mis à jour. Vous pouvez vous connecter.",
    devOtpHint: "OTP dev (SMTP non configuré)",
    orgProfileTitle: "Compléter le profil de l'organisation",
    orgProfileSubtitle: "Informations de l'entreprise. Séparé de votre profil personnel.",
    legalName: "Raison sociale",
    taxId: "N° fiscal",
    saveOrgProfile: "Enregistrer le profil organisation",
    orgProfileSaved: "Profil organisation enregistré",
    orgLogoHint: "Téléverser le logo de l'organisation (optionnel).",
    orgSectionIdentity: "Identité",
    orgSectionContact: "Contact",
    orgSectionAddress: "Adresse",
    industry: "Secteur d'activité",
    orgDescription: "À propos de l'organisation",
    orgEmail: "E-mail de l'organisation",
    city: "Ville",
    country: "Pays",
    postalCode: "Code postal",
    website: "Site web",
    organization: "Organisation",
    personalProfileTitle: "Compléter votre profil personnel",
    personalProfileSubtitle: "Vos informations personnelles au sein de cette organisation.",
    personalProfileSaved: "Profil personnel enregistré",
    personalInfo: "Informations personnelles",
    jobTitle: "Poste",
    owner: "Propriétaire",
    billing: "Abonnement",
    billingSubtitle: "Gérez votre forfait et les renouvellements.",
    currentPlan: "Forfait actuel",
    plan: "Forfait",
    dueDate: "Échéance",
    choosePlan: "Choisir un forfait",
    subscribe: "S'abonner",
    unlimitedUsers: "Utilisateurs illimités",
    unlimitedLocations: "Sites illimités",
    couponCode: "Code promo",
    applyCoupon: "Appliquer",
    assignedCoupons: "Assignés à votre organisation",
    couponApplied: "Code promo appliqué",
    couponInvalid: "Code promo invalide",
    couponCheckoutActivated: "Abonnement activé avec votre code promo — aucun paiement requis.",
    renewalWindowHint: "Renouvellement ou changement de forfait uniquement dans les 5 jours avant/après l'échéance.",
    probationBanner: "Votre organisation est en probation (forfait gratuit). Seul le propriétaire peut se connecter jusqu'à un nouvel abonnement.",
    paymentSimulated: "Paiement marqué réussi (dev).",
    sendInvite: "Envoyer une invitation",
    inviteEmailHint: "Invitez un collaborateur par e-mail. Il recevra un lien, choisira son mot de passe et vérifiera par OTP.",
    inviteSent: "Invitation envoyée",
    inviteResent: "Invitation renvoyée",
    inviteEmailFailed: "L'e-mail n'a pas pu être envoyé — vérifiez SMTP ou renvoyez plus tard",
    pendingInvites: "Invitations en attente",
    resendInvite: "Renvoyer",
    inviteFromStaff: "Inviter depuis le personnel",
    dashboard: "Tableau de Bord",
    income: "Revenus",
    expenses: "Dépenses",
    inventory: "Inventaire",
    hr: "RH",
    reports: "Rapports",
    estimates: "Devis",
    admin: "Admin",
    logout: "Déconnexion",
    totalIncome: "Revenus Totaux",
    totalExpenses: "Dépenses Totales",
    netBalance: "Solde Net",
    inventoryValue: "Valeur Inventaire",
    recentActivity: "Activité Récente",
    add: "Ajouter",
    delete: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    editUser: "Modifier l'utilisateur",
    saveChanges: "Enregistrer les modifications",
    actions: "Actions",
    source: "Source",
    amount: "Montant",
    date: "Date",
    description: "Description",
    category: "Catégorie",
    item: "Article",
    type: "Type",
    quantity: "Quantité",
    value: "Valeur",
    firstName: "Prénom",
    lastName: "Nom",
    position: "Poste",
    status: "Statut",
    documents: "Documents",
    upload: "Téléverser",
    download: "Télécharger",
    view: "Voir",
    back: "Retour",
    profile: "Mon Profil",
    address: "Adresse",
    phone: "Téléphone",
    gender: "Sexe",
    dob: "Date de Naissance",
    hireDate: "Date d'embauche",
    terminationDate: "Date de fin de contrat",
    allLocations: "Tous les Sites",
    selectLocation: "Choisir un site",
    changePassword: "Changer mot de passe",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer mot de passe",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    passwordChanged: "Mot de passe changé avec succès.",
    resetPassword: "Réinitialiser MDP",
    resetSuccess: "Réinitialisé. MDP temp: ",
    oldPassword: "Mot de passe actuel",
    oldPasswordRequired: "Le mot de passe actuel est requis",
    confirmDelete: "Confirmer la suppression",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    remove: "Supprimer",
    confirmDeactivateUser: "Désactiver cet utilisateur ? Il ne pourra plus se connecter.",
    confirmRemoveUser: "Supprimer définitivement cet utilisateur ? Cette action est irréversible.",
    userDeactivated: "Utilisateur désactivé",
    userReactivated: "Utilisateur réactivé",
    userRemoved: "Utilisateur supprimé",
    active: "Actif",
    inactive: "Inactif",
    deleteStaffConfirm: "Êtes-vous sûr de vouloir supprimer ce membre du personnel?",
    noUserAccount: "Ce membre du personnel n'a pas de compte utilisateur",
    uploadDocument: "Téléverser un document",
    documentName: "Nom du document",
    documentType: "Type de document",
    selectFile: "Sélectionner un fichier",
    updatePermissions: "Mettre à jour les permissions",
    positions: "Postes",
    noDocuments: "Aucun document téléversé",
    permissionsSelected: "permissions sélectionnées",
    perm_viewDashboard: "Voir Tableau de Bord",
    perm_viewIncome: "Voir Revenus",
    perm_addIncome: "Ajouter Revenu",
    perm_deleteIncome: "Supprimer Revenu",
    perm_viewExpenses: "Voir Dépenses",
    perm_addExpenses: "Ajouter Dépense",
    perm_deleteExpenses: "Supprimer Dépense",
    perm_manageCategories: "Gérer Catégories",
    perm_viewInventory: "Voir Inventaire",
    perm_addInventory: "Ajouter Inventaire",
    perm_updateInventory: "Modifier inventaire / signaler incidents",
    perm_deleteInventory: "Supprimer Inventaire",
    perm_manageTypes: "Gérer Types Inv.",
    perm_viewHR: "Voir RH",
    perm_addHR: "Ajouter Employé",
    perm_updateHR: "Modifier Employé",
    perm_deleteHR: "Supprimer Employé",
    perm_manageHRUploads: "Gérer Documents RH",
    perm_managePositions: "Gérer Postes",
    perm_manageDocs: "Gérer Documents",
    perm_viewReports: "Voir Rapports",
    perm_viewEstimates: "Voir Devis",
    perm_addEstimates: "Ajouter Devis",
    perm_updateEstimates: "Modifier Devis",
    perm_deleteEstimates: "Supprimer Devis",
    perm_manageEstimateTemplates: "Gérer modèles de devis",
    perm_viewAdmin: "Accès Admin",
    perm_manageAdminUsers: "Admin: onglet Gestion des utilisateurs",
    perm_manageAdminRoles: "Admin: onglet Gestion des rôles",
    perm_manageAdminConfig: "Admin: Config (sites, catégories, types, postes, sources, descriptions, emplacements)",
    adminNoSubPermission: "Vous n'avez pas la permission de gérer les paramètres. Contactez un administrateur pour accéder à la Gestion des utilisateurs, des rôles ou de la Config.",
    perm_allLocations: "Accès à Tous Les Sites",
    manage_users: "Gérer les utilisateurs (créer, modifier, supprimer, réinitialiser MDP pour tout utilisateur)",
    perm_resetUserPassword: "Réinitialiser le mot de passe (utilisateurs de votre site uniquement)",
    perm_deactivateUser: "Désactiver des utilisateurs",
    perm_removeUser: "Supprimer des utilisateurs",
    errorFillFields: "Veuillez remplir tous les champs.",
    errorDateFuture: "La date ne peut pas être dans le futur.",
    errorDatePast: "La date ne peut pas dépasser 7 jours.",
    errorNoLocation: "Veuillez sélectionner un site spécifique.",
    userManagement: "Gestion Utilisateurs",
    roleManagement: "Gestion Rôles",
    locationManagement: "Sites",
    configManagement: "Configurations",
    generateReport: "Générer Rapport",
    forecast: "Prévisions Financières",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    yearly: "Annuel",
    allTime: "Tout",
    dateRange: "Période",
    dateFrom: "Du",
    dateTo: "Au",
    last7Days: "7 derniers jours",
    thisMonth: "Ce mois",
    thisYear: "Cette année",
    last12Months: "12 derniers mois",
    incomeVsExpenses: "Revenus vs Dépenses",
    incomeBySource: "Revenus par source",
    expensesByCategory: "Dépenses par catégorie",
    financialOverview: "Vue financière",
    financialHealth: "Santé financière",
    netTrend: "Tendance du solde net",
    showCharts: "Afficher les graphiques",
    hideCharts: "Masquer les graphiques",
    downloadCSV: "Télécharger CSV",
    downloadExcel: "Télécharger Excel",
    forecastTitle: "Projections Financières",
    forecastDesc: "Basé sur la moyenne historique",
    managePermissions: "Gérer Permissions",
    roleName: "Nom du Rôle",
    permissions: "Permissions",
    expenseCategories: "Catégories Dépenses",
    inventoryTypes: "Types Inventaire",
    incomeSources: "Sources de revenus",
    expenseDescriptions: "Descriptions de dépenses",
    storagePlaces: "Emplacements de stockage",
    name: "Nom",
    nameFr: "Nom (FR)",
    metric: "Métrique",
    allMetrics: "Toutes Métriques",
    incomeOnly: "Revenus Seuls",
    expensesOnly: "Dépenses Seules",
    inventoryOnly: "Inventaire",
    specificLocation: "Site Spécifique",
    changePhoto: "Changer Photo",
    updateProfile: "Mettre à jour Profil",
    mandatoryReset: "Alerte Sécurité: Vous devez changer votre mot de passe pour continuer.",
    hierarchyForbidden: "Vous ne pouvez pas modifier ou supprimer un utilisateur au-dessus de vous dans la hiérarchie.",
    locked24hMessage: "Modification et suppression interdites après 24 h (prévention des fraudes).",
    auditLogs: "Journaux d'audit",
    perm_viewAuditLogs: "Voir les journaux d'audit",
    filterByLocation: "Site",
    filterByUser: "Utilisateur",
    searchByName: "Rechercher par nom",
    filterByPosition: "Poste",
    allPositions: "Tous les postes",
    listView: "Vue liste",
    gridView: "Vue grille",
    auditAction: "Action",
    auditResource: "Ressource",
    auditTime: "Heure",
    auditDetails: "Détails",
    auditUser: "Utilisateur",
    auditLocation: "Site",
    noAuditLogs: "Aucun journal d'audit.",
    applyFilters: "Appliquer",
    clearFilters: "Effacer",
    notifications: "Notifications",
    perm_viewNotifications: "Voir les notifications",
    noNotifications: "Aucune notification",
    themeToggle: "Basculer mode clair/sombre",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    errorNoInventory: "Aucun article d'inventaire sélectionné.",
    inventoryDeleteConfirm: "Supprimer l'article ?",
    inventoryDeleteConfirmMsg: "Voulez-vous vraiment supprimer cet article d'inventaire ?",
    inventoryUpdateTitle: "Modifier l'article",
    inventoryReportIncident: "Signaler un incident",
    inventoryOnHand: "En stock",
    inventoryOnHandShort: "Qté",
    inventoryUnitValue: "Valeur unitaire",
    inventoryUnitValueShort: "Unit.",
    inventoryTotal: "Total",
    inventoryTotalShort: "Total",
    inventoryStatus: "Statut",
    inventoryExpiry: "Expiration",
    inventoryLastUpdated: "Dernière mise à jour",
    inventoryLastUpdatedShort: "Maj",
    inventoryExpiresOn: "Expire le",
    inventoryNotes: "Notes",
    inventoryImage: "Image de l'article",
    inventoryStoragePlace: "Emplacement de stockage",
    inventoryStoragePlaceShort: "Empl.",
    inventoryStoragePlaceHint: "Rayon, bac, chambre froide, zone…",
    inventorySiteLabel: "Site",
    inventoryImageUploadFailed: "Échec du téléversement de l'image.",
    inventoryChangeImage: "Changer l'image",
    inventorySearch: "Rechercher…",
    inventoryFilterStatus: "Statut",
    inventoryFilterType: "Type",
    inventoryFilterAll: "Tous",
    inventoryExpiringSoon: "Expire dans 30 jours",
    inventoryStatus_available: "Disponible",
    inventoryStatus_damaged: "Endommagé",
    inventoryStatus_expired: "Expiré",
    inventoryStatus_missing: "Manquant",
    inventoryReason_damaged: "Endommagé / cassé",
    inventoryReason_expired: "Expiré / périmé",
    inventoryReason_stolen: "Volé / manquant",
    inventoryReason_restored: "Restauré / retrouvé",
    inventoryReason_adjustment: "Ajustement de quantité",
    inventoryIncidentReason: "Motif",
    inventoryIncidentQty: "Quantité",
    inventoryIncidentNote: "Note",
    inventoryIncidentNoteRequired: "Une note est requise pour les incidents endommagé ou volé.",
    inventoryIncidentQtyInvalid: "Saisissez une quantité valide pour cet incident.",
    inventoryIncidentSuccess: "Incident enregistré.",
    inventoryIncidentFailed: "Échec de l'enregistrement de l'incident.",
    inventoryAdded: "Article d'inventaire ajouté",
    inventoryUpdated: "Article d'inventaire mis à jour",
    inventoryRemoved: "Article d'inventaire supprimé",
    inventoryNoPermAdd: "Vous n'avez pas la permission d'ajouter des articles.",
    inventoryNoPermUpdate: "Vous n'avez pas la permission de modifier l'inventaire.",
    inventoryNoPermDelete: "Vous n'avez pas la permission de supprimer des articles.",
    inventoryHealth: "Santé de l'inventaire",
    inventoryAvailableValue: "Valeur disponible",
    inventoryLossValue: "Valeur des pertes",
    inventoryUnitsLost: "Unités perdues",
    inventoryDamagedUnits: "Endommagé",
    inventoryExpiredUnits: "Expiré",
    inventoryStolenUnits: "Volé",
    inventoryExpiringSoonCount: "Expire bientôt",
    inventoryLossesByReason: "Pertes d'inventaire par motif",
    inventoryLossesSheet: "Pertes inventaire",
    inventoryNoItems: "Aucun article ne correspond aux filtres.",
    newHire: "Nouvelle embauche",
    staffTerminationDate: "Date de fin de contrat",
    staffDeleted: "Compte employé supprimé",
    incomeDeleted: "Revenu supprimé",
    expenseDeleted: "Dépense supprimée",
    inventoryDeleted: "Article d'inventaire supprimé",
    reportDownloaded: "Rapport téléchargé",
    newEstimate: "Nouveau devis",
    editEstimate: "Modifier le devis",
    estimateTitle: "Titre",
    estimateNumber: "N° devis",
    estimateStatus: "Statut",
    estimateCustomer: "Client",
    estimateBusiness: "Entreprise",
    estimateLineItems: "Lignes",
    estimatePreview: "Aperçu",
    estimateTemplate: "Modèle",
    estimateIndustryTemplates: "Modèles métiers",
    estimateUserTemplates: "Vos modèles",
    archiveAsTemplate: "Archiver comme modèle",
    estimateLogo: "Logo",
    primaryColor: "Couleur principale",
    accentColor: "Couleur d'accent",
    estimateLayout: "Mise en page",
    layoutClassic: "Classique",
    layoutModern: "Moderne",
    layoutCompact: "Compacte",
    validUntil: "Valable jusqu'au",
    issueDate: "Date d'émission",
    taxRate: "Taxe %",
    subtotal: "Sous-total",
    taxAmount: "Taxe",
    total: "Total",
    unitPrice: "Prix unitaire",
    unit: "Unité",
    lineTotal: "Total ligne",
    terms: "Conditions",
    notes: "Notes",
    exportCsv: "Exporter CSV",
    exportExcel: "Exporter Excel",
    exportPdf: "Imprimer / PDF",
    copyPlainText: "Copier le texte",
    estimateDraft: "Brouillon",
    estimateSent: "Envoyé",
    estimateAccepted: "Accepté",
    estimateRejected: "Refusé",
    estimateArchived: "Archivé",
    noEstimates: "Aucun devis pour le moment.",
    searchEstimates: "Rechercher des devis…",
    addLineItem: "Ajouter une ligne",
    removeLineItem: "Retirer",
    customerName: "Nom du client",
    customerEmail: "Email client",
    customerPhone: "Téléphone client",
    customerAddress: "Adresse client",
    businessName: "Nom de l'entreprise",
    businessAddress: "Adresse de l'entreprise",
    businessPhone: "Téléphone de l'entreprise",
    estimateSaved: "Devis enregistré",
    estimateDeleted: "Devis supprimé",
    templateArchived: "Enregistré comme modèle",
    pickTemplate: "Partir d'un modèle",
    blankEstimate: "Devis vierge",
  }
};

export const convertCurrency = (amount: number, currencyCode: string) => {
  const currency = CURRENCIES[currencyCode as keyof typeof CURRENCIES] || CURRENCIES.XAF;
  return amount * currency.rate;
};

export const formatCurrency = (amount: number, currencyCode: string) => {
  const currency = CURRENCIES[currencyCode as keyof typeof CURRENCIES] || CURRENCIES.XAF;
  const converted = convertCurrency(amount, currencyCode);
  return new Intl.NumberFormat('fr-FR', {
    style: 'currency',
    currency: currency.code,
    maximumFractionDigits: currency.precision,
    minimumFractionDigits: currency.precision,
  }).format(converted);
};

export const getTranslated = (item: any, lang: string) => {
  if (!item) return '';
  return item[lang] || item['en'] || 'N/A';
};

/** Fraud prevention: records older than 24 hours cannot be edited or deleted (applies to income, expense, inventory registration delete/edit). */
export const isLockedAfter24Hours = (createdAt: string | Date | undefined): boolean => {
  if (!createdAt) return false;
  const created = typeof createdAt === 'string' ? new Date(createdAt) : createdAt;
  return Date.now() - created.getTime() > 24 * 60 * 60 * 1000;
};

const LOSS_REASONS: InventoryEventReason[] = ['damaged', 'expired', 'stolen'];

export const isInventoryLossReason = (reason: InventoryEventReason) => LOSS_REASONS.includes(reason);

export const isExpiringSoon = (expiresOn: string | null | undefined, withinDays = 30): boolean => {
  if (!expiresOn) return false;
  const exp = new Date(expiresOn);
  if (Number.isNaN(exp.getTime())) return false;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const limit = new Date(today);
  limit.setDate(limit.getDate() + withinDays);
  return exp >= today && exp <= limit;
};

export const isPastExpiry = (expiresOn: string | null | undefined): boolean => {
  if (!expiresOn) return false;
  const exp = new Date(expiresOn);
  if (Number.isNaN(exp.getTime())) return false;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return exp < today;
};

/** Display status for an inventory line (on-hand + expiry + last stored status). */
export const deriveInventoryStatus = (item: Pick<InventoryItem, 'quantity' | 'status' | 'expiresOn'>): InventoryStatus => {
  if (isPastExpiry(item.expiresOn)) return 'expired';
  if ((item.quantity ?? 0) <= 0) {
    if (item.status === 'damaged' || item.status === 'expired' || item.status === 'missing') return item.status;
    return 'missing';
  }
  if (item.status === 'damaged') return 'damaged';
  return 'available';
};

/** Next status after applying an incident that changes on-hand quantity. */
export const statusAfterIncident = (
  reason: InventoryEventReason,
  nextQty: number,
  expiresOn?: string | null
): InventoryStatus => {
  if (isPastExpiry(expiresOn)) return 'expired';
  if (nextQty <= 0) {
    if (reason === 'stolen') return 'missing';
    if (reason === 'damaged') return 'damaged';
    if (reason === 'expired') return 'expired';
    return 'missing';
  }
  if (reason === 'damaged') return 'damaged';
  return 'available';
};

// Helper for 7-day rule
export const isDateWithinLimit = (dateString: string) => {
  const inputDate = new Date(dateString);
  const today = new Date();
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(today.getDate() - 7);

  // Reset hours to compare dates only
  inputDate.setHours(0, 0, 0, 0);
  today.setHours(0, 0, 0, 0);
  sevenDaysAgo.setHours(0, 0, 0, 0);

  return inputDate >= sevenDaysAgo && inputDate <= today;
};