import React from 'react';
import { FileText } from 'lucide-react';
import {
  LegalDocumentLayout,
  LegalList,
  LegalParagraph,
  LegalSection,
  LegalSubSection,
  type LegalDocumentMeta,
} from './LegalDocumentLayout';

const SUPPORT_EMAIL = (
  <a href="mailto:helpdesk@aheteici.com" className="text-primary-600 hover:underline">
    helpdesk@aheteici.com
  </a>
);

type Props = {
  title: string;
  meta: LegalDocumentMeta;
};

export const TermsAndConditionsEn: React.FC<Props> = ({ title, meta }) => (
  <LegalDocumentLayout
    icon={FileText}
    title={title}
    meta={meta}
    subtitle='These Terms and Conditions (the "Terms") govern access to and use of the Agrimarket Connect platform and services (the "Platform"). Please read them carefully.'
  >
      <LegalSection title="1. Parties and Operator">
        <LegalParagraph>The Platform is operated by:</LegalParagraph>
        <LegalList
          items={[
            <>Legal entity: Achète Tout Ici Sarl</>,
            <>Business address: Dogbong, Douala, Littoral, Cameroon</>,
            <>Support email: {SUPPORT_EMAIL}</>,
            <>Trade/brand name: Agrimarket Connect</>,
          ]}
        />
        <LegalParagraph>
          In these Terms, Achète Tout Ici Sarl is referred to as &ldquo;Achète Tout Ici&rdquo;, &ldquo;we&rdquo;,
          &ldquo;us&rdquo;, or &ldquo;our&rdquo;.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="2. Scope">
        <LegalParagraph>These Terms apply to:</LegalParagraph>
        <LegalList
          items={[
            <>the Producer Marketplace (where Producers list products/services and Clients place orders),</>,
            <>the Retail Store (ATI retail offers sold via the Platform), and</>,
            <>
              related features such as user accounts, wallets, coupons/promotions, referrals, chat, support,
              disputes, notifications, and administrative moderation.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection title="3. Acceptance">
        <LegalParagraph>
          By accessing or using the Platform, you agree to be bound by these Terms. If you do not agree, do not use
          the Platform.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="4. Definitions">
        <LegalParagraph>For purposes of these Terms:</LegalParagraph>
        <LegalList
          items={[
            <>&ldquo;Account&rdquo; means your Platform user account.</>,
            <>&ldquo;Client&rdquo; means a user purchasing products/services.</>,
            <>&ldquo;Producer&rdquo; means a user offering products/services.</>,
            <>&ldquo;Retail Store&rdquo; means ATI retail offers available via the Platform.</>,
            <>&ldquo;Offer&rdquo; means a product or service listing on the Platform.</>,
            <>&ldquo;Order&rdquo; means a purchase transaction initiated via the Platform.</>,
            <>&ldquo;Wallet&rdquo; means the Platform balance ledger associated with a user.</>,
            <>&ldquo;Coupon&rdquo; means a promotional code/discount issued by the Platform.</>,
            <>&ldquo;Referral Program&rdquo; means a rewards program for inviting new users.</>,
            <>&ldquo;Support Session&rdquo; means a support conversation thread on the Platform.</>,
            <>&ldquo;AI Assistant&rdquo; means automated support responses generated by an AI system.</>,
            <>&ldquo;Dispute&rdquo; means a complaint or disagreement relating to an Order.</>,
            <>
              &ldquo;Content&rdquo; means text, images, files, reviews, messages, evidence, listings, and other
              information submitted to or generated on the Platform.
            </>,
            <>
              &ldquo;Payment Method&rdquo; means a withdrawal method registered by a Producer (such as mobile money or
              bank details), where supported.
            </>,
          ]}
        />
        <LegalParagraph>If a term is not defined in these Terms, it has its ordinary meaning.</LegalParagraph>
      </LegalSection>

      <LegalSection title="5. Eligibility and Accounts">
        <LegalSubSection title="5.1 Eligibility">
          <LegalParagraph>You may use the Platform only if you:</LegalParagraph>
          <LegalList
            items={[
              <>are at least 18 years old (or the age of majority under applicable law);</>,
              <>have the legal capacity to enter into a binding agreement;</>,
              <>are not prohibited from using the Platform under applicable law; and</>,
              <>provide accurate and complete information.</>,
            ]}
          />
          <LegalParagraph>
            If you use the Platform on behalf of a business or other entity, you represent that you have authority to
            bind that entity to these Terms.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="5.2 Registration and Account Security">
          <LegalParagraph>To access certain features, you must create an Account. When you create an Account, you agree that:</LegalParagraph>
          <LegalList
            items={[
              <>
                <strong>Uniqueness:</strong> each Account must be created with a unique email address and phone number
                where required by the Platform.
              </>,
              <>
                <strong>Accuracy:</strong> you will provide accurate information and keep it up to date.
              </>,
              <>
                <strong>Security:</strong> you will keep your login credentials confidential and secure and promptly
                notify us if you suspect unauthorized access.
              </>,
              <>
                <strong>Responsibility:</strong> you are responsible for all activity under your Account.
              </>,
            ]}
          />
          <LegalParagraph>
            We may require verification steps (including one-time passwords (OTPs)) for security-sensitive actions.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="5.3 Roles and Profiles">
          <LegalParagraph>The Platform supports different user roles and profiles, including:</LegalParagraph>
          <LegalList items={[<>Clients who place Orders; and</>, <>Producers who create Offers and fulfill Orders.</>]} />
          <LegalParagraph>
            Some actions require that you complete a corresponding profile (e.g., a Producer profile for listing
            Offers; a Client profile for placing Orders). If required profile information is missing or incomplete, you
            may not be able to use certain features. All users on the platform are clients by default, which means that
            even approved producers can buy from other producers and in the retail store.
          </LegalParagraph>
          <LegalParagraph>
            <strong>Producer validation.</strong> Producers may be subject to internal review and may have statuses such
            as pending, validated/approved, or suspended. The Platform may restrict access to listing or order
            fulfillment functionality if a Producer is not validated or is suspended.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="5.4 Suspension and Termination">
          <LegalParagraph>We may suspend, restrict, or terminate your access to the Platform at any time if we reasonably believe that:</LegalParagraph>
          <LegalList
            items={[
              <>you violated these Terms or applicable law;</>,
              <>you engaged in fraud, abuse, harassment, or other harmful conduct;</>,
              <>your Account security is compromised; or</>,
              <>
                continuing to provide the Platform to you could create risk for the Platform, other users, or third
                parties.
              </>,
            ]}
          />
          <LegalParagraph>
            You may stop using the Platform at any time. Termination does not automatically cancel Orders that are
            already in progress and does not relieve you of obligations incurred before termination. Wallet balances and
            pending withdrawal requests may be subject to verification and compliance checks.
          </LegalParagraph>
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="6. Producer Marketplace : Listings and Conduct">
        <LegalSubSection title="6.1 Producer Obligations">
          <LegalParagraph>If you are a Producer, you agree to:</LegalParagraph>
          <LegalList
            items={[
              <>
                create Offers that are accurate, complete, and not misleading (including description, unit, quantity,
                price, delivery availability, and location);
              </>,
              <>ensure you have the right to sell the listed products or provide the listed services;</>,
              <>
                comply with all applicable laws (including product safety, consumer protection, and any licensing
                requirements);
              </>,
              <>maintain sufficient stock/availability consistent with your Offers; and</>,
              <>
                fulfill Orders in good faith, in a timely manner, and consistent with the selected delivery/pickup
                method.
              </>,
            ]}
          />
        </LegalSubSection>

        <LegalSubSection title="6.2 Prohibited Listings and Content">
          <LegalParagraph>You must not list, offer, transmit, or otherwise make available any Content that:</LegalParagraph>
          <LegalList
            items={[
              <>is unlawful, fraudulent, deceptive, or misleading;</>,
              <>infringes intellectual property or other rights of third parties;</>,
              <>is dangerous, harmful, or restricted by law without required authorizations;</>,
              <>contains malicious code or attempts to interfere with the Platform; or</>,
              <>
                violates the dignity, privacy, or safety of others (including harassment or hate speech).
              </>,
            ]}
          />
        </LegalSubSection>

        <LegalSubSection title="6.3 Platform Moderation">
          <LegalParagraph>We may review, moderate, disable, or remove Offers or other Content and may suspend Producer functionality where necessary to:</LegalParagraph>
          <LegalList
            items={[
              <>comply with law or lawful requests;</>,
              <>protect users, the Platform, or third parties; or</>,
              <>enforce these Terms and Platform policies.</>,
            ]}
          />
          <LegalParagraph>We are not obligated to monitor all Content, but we may do so.</LegalParagraph>
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="7. Retail Store (ATI Retail Offers)">
        <LegalParagraph>
          The Retail Store provides access to offers designated as retail/ATI offers. Retail Store purchases may differ
          from Producer Marketplace purchases in pricing, fees, coupon eligibility, and fulfillment rules.
        </LegalParagraph>
        <LegalList
          items={[
            <>
              <strong>Retail-only eligibility.</strong> Certain offers are available only through the Retail Store.
            </>,
            <>
              <strong>Coupon channels.</strong> Coupons may be limited to Retail Store purchases, Producer Marketplace
              purchases, or both.
            </>,
            <>
              <strong>Stock/availability.</strong> Retail offers are subject to availability and may be limited by
              inventory.
            </>,
          ]}
        />
        <LegalParagraph>
          Where the Platform indicates that a purchase is a Retail Store order, the seller may be Achète Tout Ici (or a
          designated retail operator) rather than an independent Producer. The Platform will indicate the seller where
          required.
        </LegalParagraph>
        <LegalParagraph>
          If any conflict exists between Retail Store-specific checkout information and these Terms, these Terms control
          unless explicitly stated otherwise.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="8. Orders and Contract Formation">
        <LegalSubSection title="8.1 Order Process">
          <LegalParagraph>
            <strong>Producer Marketplace.</strong> On the Producer Marketplace, the typical lifecycle is:
          </LegalParagraph>
          <LegalList
            items={[
              <>Client places an Order based on a Producer&rsquo;s Offer.</>,
              <>Producer validates/accepts the Order.</>,
              <>Client completes payment where required by the Platform.</>,
              <>The producer prepares the goods/services.</>,
              <>
                Producer marks the Order for delivery/transit (or pickup readiness where supported).
              </>,
              <>Client confirms receipt/delivery and the Order is completed.</>,
            ]}
          />
          <LegalParagraph>
            <strong>Retail Store.</strong> Retail Store checkout may confirm orders immediately after successful
            creation, subject to Platform rules and availability.
          </LegalParagraph>
          <LegalParagraph>
            <strong>Contract formation.</strong> When a Client places an Order, the Client makes an offer to purchase.
            The contract between Client and Producer is formed when the Order is accepted/validated (or otherwise
            confirmed by the Platform&rsquo;s checkout flow). We may facilitate this process but are not a party to the
            contract between Client and Producer, except for Retail Store orders where the seller may be the
            Platform&rsquo;s retail operator.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="8.2 Order Statuses (Operational)">
          <LegalParagraph>
            Order status transitions are operational features used to reflect the progress of an Order. Typical statuses
            may include, without limitation: pending validation, confirmed awaiting payment, paid/in preparation, in
            transit, delivered, completed, cancelled, and dispute.
          </LegalParagraph>
          <LegalParagraph>
            Certain status changes may be restricted to specific parties (e.g., Producer vs Client) and may depend on the
            current status.
          </LegalParagraph>
          <LegalParagraph>
            You agree to use the status tools honestly and promptly (for example, only confirm receipt if you have
            actually received the goods or service).
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="8.3 Errors and Availability">
          <LegalParagraph>Offers and Orders may be rejected, cancelled, or adjusted if, for example:</LegalParagraph>
          <LegalList
            items={[
              <>inventory is insufficient;</>,
              <>an Offer is suspended or removed;</>,
              <>there is suspected fraud or misuse; or</>,
              <>there are technical errors or pricing display issues.</>,
            ]}
          />
          <LegalParagraph>We may correct errors and take reasonable steps to notify affected users.</LegalParagraph>
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="9. Pricing, Fees, Taxes">
        <LegalParagraph>All orders placed on the platform are subject to fees and service charges. Prices are displayed in the currency supported by the Platform and may be subject to:</LegalParagraph>
        <LegalList
          items={[
            <>A 16.5% service charge applies to all orders placed on the main marketplace (where applicable);</>,
            <>A 3% service charge applies to all orders placed in the shop (where applicable).</>,
            <> 1.5% withdrawal fee applies. These fees are charged to us by Tranzak for processing your payment.</>,
            <>wallet top-up fee: This is the commission we collect on each order successfully sold by a producer before the funds are deposited into their wallet. We deduct 5% of this amount.</>,
            <>delivery or pickup handling fees (where applicable); and</>,
            <>wallet top-up fee: 0%. All wallet top-up transactions are free.</>,
            <>taxes or legally required charges, if any.</>,
          ]}
        />
        <LegalParagraph>
          You are responsible for any taxes that apply to your transactions unless the Platform explicitly states
          otherwise.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="10. Coupons, Promotions, and Referrals">
        <LegalSubSection title="10.1 Coupons (Channel and Limits)">
          <LegalParagraph>
            Coupons and promotions are offered at our discretion and may be subject to eligibility criteria, expiry
            dates, minimum order amounts, and other restrictions.
          </LegalParagraph>
          <LegalList
            items={[
              <>
                <strong>Channel scope.</strong> A coupon may be limited to Marketplace purchases, Retail Store
                purchases, or both, as determined by the Platform at the time of validation/redemption.
              </>,
              <>
                <strong>Per-user limits.</strong> A coupon may have a per-user redemption limit. We may refuse redemption
                if limits are exceeded or if we reasonably suspect abuse.
              </>,
              <>
                <strong>Validation.</strong> Coupon eligibility and discount calculations may be validated server-side at
                checkout. You must not attempt to manipulate totals or redeem coupons outside their permitted channel or
                limits.
              </>,
            ]}
          />
          <LegalParagraph>Coupons have no cash value and cannot be exchanged for cash unless required by law.</LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="10.2 Referral Program">
          <LegalParagraph>The Platform may offer a Referral Program. If available, it may include referral codes and reward amounts, which may be subject to:</LegalParagraph>
          <LegalList
            items={[
              <>eligibility rules,</>,
              <>first-order or other activity triggers,</>,
              <>budget caps for the program,</>,
              <>anti-fraud checks (including rejecting suspicious referrals), and</>,
              <>program-specific terms (which may be provided via a link in the Platform).</>,
            ]}
          />
          <LegalParagraph>We may modify, suspend, or terminate a Referral Program at any time.</LegalParagraph>
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="11. Payments, Wallets, and Withdrawals">
        <LegalSubSection title="11.1 Payments">
          <LegalParagraph>
            Payments may be processed via third-party providers. You authorize us and our providers to process payments
            on your behalf, including initiating payment requests, confirming payment statuses, and handling payment
            notifications.
          </LegalParagraph>
          <LegalParagraph>
            Payment processing depends on external systems. We do not guarantee that payments will be completed in a
            specific timeframe.
          </LegalParagraph>
          <LegalParagraph>
            You agree not to initiate chargebacks or reversals fraudulently. If reversals occur, we may take appropriate
            action including suspending accounts, reversing credits, or pursuing recovery where legally permitted.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="11.2 Wallet">
          <LegalParagraph>
            The Platform may maintain a Wallet balance for users. Wallet balances reflect Platform ledger entries and may
            be updated based on transactions such as purchases, credits, referral rewards, adjustments, and withdrawals.
          </LegalParagraph>
          <LegalParagraph>
            Wallet balances are not bank accounts and do not earn interest unless explicitly stated.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="11.3 Withdrawals (Producers)">
          <LegalParagraph>If you are a Producer, you may request withdrawals subject to:</LegalParagraph>
          <LegalList
            items={[
              <>minimum withdrawal amounts (10.000 FCFA);</>,
              <>
                having an eligible Payment Method registered on the Platform (Orange, MTN, Bank);
              </>,
              <>sufficient Wallet balance; and</>,
              <>security verification steps (including OTP-based verification) when required.</>,
            ]}
          />
          <LegalParagraph>
            Withdrawal requests may be reviewed and approved or rejected by Platform administrators. We may request
            additional information for compliance or fraud-prevention purposes.
          </LegalParagraph>
          <LegalParagraph>
            <strong>OTP verification.</strong> For security, Producers may be required to confirm a one-time password
            (OTP) sent to the phone number on file before certain sensitive actions (including withdrawals and certain
            profile changes).
          </LegalParagraph>
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="12. Delivery, Pickup, and Receipt">
        <LegalParagraph>
          The Platform may support delivery and/or pickup options, including home delivery and pickup points.
        </LegalParagraph>
        <LegalList
          items={[
            <>
              <strong>Pickup points.</strong> If you choose pickup, you are responsible for arriving at the designated
              pickup point and following instructions for pickup.
            </>,
            <>
              <strong>Delivery information.</strong> You are responsible for providing accurate delivery or pickup
              information.
            </>,
          ]}
        />
        <LegalParagraph>
          Risk of loss and transfer of responsibility may depend on the transaction type, the delivery method, and
          applicable law.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="13. Cancellations, Returns, Refunds">
        <LegalParagraph>
          Cancellations may be permitted in certain circumstances depending on the Order status and Platform rules. If
          a return or refund mechanism is offered, it will be described in the Platform or a supplemental policy.
        </LegalParagraph>
        <LegalParagraph>
          If the Platform does not provide an automated refund flow for a particular transaction type, refunds (if any)
          may be handled through the dispute and settlement process described below, subject to applicable law.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="14. Disputes and Evidence">
        <LegalParagraph>
          If you have an issue with an Order, you may initiate a Dispute through the Platform where available. You may be
          required to provide details and upload supporting evidence (such as photos or documents).
        </LegalParagraph>
        <LegalParagraph>
          Dispute evidence may be visible only to relevant participants (e.g., the parties to the Order) and Platform
          administrators.
        </LegalParagraph>
        <LegalParagraph>
          We may review disputes, facilitate communication, and take administrative actions, but we do not guarantee a
          particular outcome.
        </LegalParagraph>
        <LegalParagraph>
          You agree that evidence you upload must be truthful, accurate, and lawful, and must not violate third-party
          rights.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="15. Support, AI Assistant, and Handover to Agents">
        <LegalParagraph>
          The Platform may provide support through support chat sessions, including an AI Assistant. You acknowledge and
          agree that:
        </LegalParagraph>
        <LegalList
          items={[
            <>AI responses are automated and may be inaccurate or incomplete.</>,
            <>AI support is not professional advice (legal, medical, financial, or otherwise).</>,
            <>You are responsible for verifying information before acting on it.</>,
            <>
              Where supported, an AI support session may be handed over to a human support agent. Support agents may
              have access to the conversation history for the purpose of providing support.
            </>,
            <>
              Some support messages or fields may be internal to administrators and not visible to end-users.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection title="16. Communications and Notifications">
        <LegalParagraph>
          We may send you communications and notifications related to account security (e.g., OTPs), order status
          updates, support interactions, and platform announcements.
        </LegalParagraph>
        <LegalParagraph>
          Delivery of notifications depends on third-party services and may be best-effort. You are responsible for
          maintaining accurate contact information.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="17. User-Generated Content, Reviews, and License">
        <LegalParagraph>
          You may submit Content such as Offer descriptions, reviews, ratings, messages, and dispute evidence. You retain
          ownership of your Content, but you grant us a non-exclusive, worldwide, royalty-free license to use, host,
          store, reproduce, and display your Content as needed to operate, improve, and promote the Platform.
        </LegalParagraph>
        <LegalParagraph>We may remove or restrict Content that violates these Terms or applicable law.</LegalParagraph>
      </LegalSection>

      <LegalSection title="18. Prohibited Conduct">
        <LegalParagraph>You must not:</LegalParagraph>
        <LegalList
          items={[
            <>use the Platform for fraud, scams, or illegal activity;</>,
            <>harass, threaten, or harm others;</>,
            <>attempt to bypass Platform security measures;</>,
            <>scrape or harvest data without permission; or</>,
            <>interfere with Platform operations.</>,
          ]}
        />
        <LegalParagraph>
          <strong>Chat restrictions.</strong> To protect users, the Platform may restrict sharing personal contact
          information (such as phone numbers and email addresses) or links within chat. Attempts to circumvent these
          restrictions may lead to account action.
        </LegalParagraph>
        <LegalParagraph>
          You agree not to request or share off-platform payment instructions through Platform chat or otherwise use the
          Platform to facilitate transactions outside the Platform in a way that defeats Platform protections, fees, or
          dispute processes.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="19. Privacy and Data">
        <LegalParagraph>
          We process personal data in accordance with our Privacy Policy (to be provided or published separately). We may
          retain data related to account security, support conversations, orders and transactions, dispute evidence, and
          audit logs as necessary for providing the Platform, compliance, fraud prevention, and record-keeping.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="20. Intellectual Property">
        <LegalParagraph>
          The Platform and its content (excluding user-submitted Content) are owned by or licensed to us and are
          protected by intellectual property laws. You may not use our trademarks or branding without permission.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="21. Disclaimer of Warranties">
        <LegalParagraph>
          To the maximum extent permitted by law, the Platform is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; without warranties of any kind. We do not warrant that the Platform will be uninterrupted,
          error-free, secure, or free of harmful components.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="22. Limitation of Liability">
        <LegalParagraph>To the maximum extent permitted by law:</LegalParagraph>
        <LegalList
          items={[
            <>We are not liable for indirect, incidental, consequential, special, or punitive damages.</>,
            <>
              Our aggregate liability arising out of or relating to the Platform will not exceed the amounts (if any) you
              paid to us in the three (3) months preceding the event giving rise to the claim, unless a higher liability
              is required by applicable law.
            </>,
            <>Nothing in these Terms limits liability that cannot be excluded under applicable law.</>,
          ]}
        />
      </LegalSection>

      <LegalSection title="23. Indemnity">
        <LegalParagraph>
          You agree to indemnify and hold harmless Achète Tout Ici Sarl and its directors, officers, employees, and agents
          from claims, liabilities, damages, and expenses (including reasonable legal fees) arising out of or related to:
        </LegalParagraph>
        <LegalList
          items={[
            <>your use of the Platform,</>,
            <>your Content,</>,
            <>your breach of these Terms, or</>,
            <>your violation of any law or third-party right.</>,
          ]}
        />
      </LegalSection>

      <LegalSection title="24. Changes to the Platform and Terms">
        <LegalParagraph>
          We may modify the Platform and these Terms from time to time. If we make material changes, we will take
          reasonable steps to notify you (e.g., through the Platform or via email). Continued use of the Platform after
          changes take effect constitutes acceptance of the updated Terms.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="25. Force Majeure">
        <LegalParagraph>
          We are not liable for delays or failures in performance resulting from events beyond our reasonable control,
          including natural disasters, network failures, strikes, government actions, or disruptions to third-party
          providers.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="26. Governing Law; Dispute Resolution (Internal → Arbitration → Courts)">
        <LegalSubSection title="26.1 Internal Complaint Process">
          <LegalParagraph>
            Before initiating arbitration or court proceedings, you agree to first contact us to attempt to resolve the
            issue informally.
          </LegalParagraph>
          <LegalList
            items={[
              <>
                <strong>How to contact:</strong> email {SUPPORT_EMAIL}
              </>,
              <>
                <strong>Information to include:</strong> your Account identifier, order/session reference (if any),
                description of the issue, and any supporting evidence.
              </>,
            ]}
          />
          <LegalParagraph>We will make reasonable efforts to respond within a reasonable time.</LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="26.2 Arbitration">
          <LegalParagraph>
            If the dispute is not resolved through the internal complaint process, you agree that disputes arising out
            of or relating to these Terms or the Platform will be submitted to binding arbitration.
          </LegalParagraph>
          <LegalParagraph>
            <strong>Arbitration details (to be finalized):</strong> The seat/venue, administering institution (if any),
            arbitration rules, number of arbitrators, and language of proceedings will be specified in a supplemental
            notice or policy published by the Platform. If not specified, the parties will use a reasonable arbitration
            framework consistent with Cameroon law.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="26.3 Courts for Enforcement">
          <LegalParagraph>To the extent permitted by law, the courts of Cameroon shall have jurisdiction for:</LegalParagraph>
          <LegalList
            items={[
              <>enforcement of an arbitration award; and</>,
              <>any matters that are not subject to arbitration under applicable law.</>,
            ]}
          />
        </LegalSubSection>
      </LegalSection>

      <LegalSection title="27. Miscellaneous">
        <LegalSubSection title="27.1 Severability">
          <LegalParagraph>
            If any provision of these Terms is held invalid or unenforceable, the remaining provisions remain in full
            force and effect.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="27.2 Assignment">
          <LegalParagraph>
            You may not assign your rights or obligations under these Terms without our prior written consent. We may
            assign our rights and obligations as part of a merger, acquisition, or sale of assets.
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="27.3 Waiver">
          <LegalParagraph>Failure to enforce any provision is not a waiver of that provision.</LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="27.4 Entire Agreement">
          <LegalParagraph>
            These Terms constitute the entire agreement between you and us regarding the Platform, except where
            supplemented by additional policies published by the Platform (such as a Privacy Policy or program-specific
            terms).
          </LegalParagraph>
        </LegalSubSection>

        <LegalSubSection title="27.5 Contact">
          <LegalParagraph>For questions about these Terms, contact {SUPPORT_EMAIL}.</LegalParagraph>
        </LegalSubSection>
      </LegalSection>
    </LegalDocumentLayout>
);
